[kde] RpQt.cpp: Fix a build error in the Qt4 (KDE4) build.
src/kde/RpQt.cpp: In function 'QUrl localizeQUrl(const QUrl&)':
src/kde/RpQt.cpp:113:26: error: 'class QString' has no member named 'empty'
   if (!qs_local_filename.empty()) {
                          ^

QString::empty() doesn't exist; it's QString::isEmpty(). This was a
copy/paste error from an std::string, which *does* have an empty()
function.

This fixes a regression from commit eef656926e46b1aac81d7963bbe6f605fbafbd8c.
([kde] RpQt: New functions localizeQUrl() and openQUrl().)