[librptexture] ARM NEON code: Use vreinterpret*() functions.
Both clang and MSVC appear to be rather lax with regards to vector
conversions, e.g. implicitly converting from 32x4 to 8x16.

gcc, by default, complains about it:

note: use '-flax-vector-conversions' to permit conversions between vectors with differing element types or numbers of subparts
error: cannot convert '__Uint32x4_t' to 'uint8x16_t'

Instead of adding '-flax-vector-conversions', add macros to make use of
vtbl with the vinterpret*() functions. Note that the vinterpret*()
functions don't change the resulting assembly at all; they merely specify
the explicit intent for the vector conversion.

Also, there are no vinterpret*() functions for the multi-vector types,
e.g. uint32x4x4_t; only for the single-vector types.