[librpcpuid] cpu_dispatch.h: Fix ARM64EC handling.
Add a !_M_ARM64EC check to the AMD64 line. Otherwise, ARM64EC will be
misdetected as AMD64.

  cpuflags_arm.c
src\librpcpuid\cpuflags_arm.c(13,1): error C1189: #error:  Do not compile cpuflags_arm.c on non-ARM CPUs!

This fixes a regression from commit d9eb93eb844012c3de3fa9b6f4352c3bc1fda2ed.
([librpcpuid] cpu_dispatch.h: Add RP_CPU_ARCH_NAME.)