[win32] RP_XAttrView::Initialize(): Move the Config check after the `fe` declaration.
MSVC complained about it due to the use of goto:

src\win32\RP_XAttrView.cpp(398): error C4533: initialization of 'fe' is skipped by 'goto cleanup'
  src\win32\RP_XAttrView.cpp(327): note: see declaration of 'fe'
  src\win32\RP_XAttrView.cpp(398): note: see declaration of 'cleanup'