[win32] DllMain.cpp: _Check_return_ should be before STDAPI.
This worked with MSVC 2017 15.6 and earlier, but broke with 15.7:

src\win32\dllmain.cpp(142): error C2059: syntax error: ''
src\win32\dllmain.cpp(143): error C2143: syntax error: missing ';' before '{'
src\win32\dllmain.cpp(143): error C2447: '{': missing function header (old-style formal list?)