[kde/tests] Rom*Test.cpp: Explicitly #include <QtCore/QLocale>.
The KDE4 builds failed on Ubuntu 16.04:

[ 79%] Building CXX object src/kde/tests/kde4/CMakeFiles/RomDataViewTest_kde4.dir/__/RomDataViewTest.cpp.o
src/kde/tests/RomDataViewTest.cpp: In constructor ‘RomPropertiesKDE4::Tests::RomDataViewTest::RomDataViewTest()’:
src/kde/tests/RomDataViewTest.cpp:66:3: error: incomplete type ‘QLocale’ used in nested name specifier
   QLocale::setDefault(QLocale(QLatin1String("C.UTF-8")));
   ^
src/kde/tests/RomDataViewTest.cpp:66:55: error: invalid use of incomplete type ‘class QLocale’
   QLocale::setDefault(QLocale(QLatin1String("C.UTF-8")));
                                                       ^
In file included from /usr/include/qt4/QtGui/QApplication:1:0,
                 from src/kde/tests/kde4/../../RpQt.hpp:18,
                 from src/kde/tests/RomDataViewTest.cpp:26:
/usr/include/qt4/QtGui/qapplication.h:81:7: note: forward declaration of ‘class QLocale’
 class QLocale;
       ^

(cherry picked from commit e03f02880060ea759831d637daa5a4de3724f941)