Remove u8ostringstream.
While it worked fine on Linux, it seems MSVC's implementation depends
on a static variable that's marked as dllimport, which isn't allowed.

https://stackoverflow.com/questions/48716223/compile-error-for-char-based-stl-stream-containers-in-visual-studio

include\xlocnum(255,1): error C2491: 'std::numpunct<_Elem>::id':
definition of dllimport static data member not allowed

Instead of trying to work around this, just remove u8ostringstream.
It's slightly less efficient to use ostringstream and convert to
u8string, but oh well.