[librpbase] ConfReader.cpp: Use llabs() instead of std::abs().
clang on Mac OS X couldn't figure out the correct type with std::abs():

src/librpbase/config/ConfReader.cpp:118:7: error: call to 'abs' is ambiguous
                if (std::abs(cur_time - d->conf_last_checked) < 2) {
                    ^~~~~~~~