Adjustments to get the build working with ClangCL 22 on MSVC 2026.
NOTE: The ClangCL build is currently *broken*, mostly because the .rc
files cannot be compiled at the moment. Windows RC doesn't like the
clang headers:

C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\Llvm\x64\lib\clang\22\include\__stddef_ptrdiff_t.h(15): fatal error RC1012: mismatched parenthesis : missing '

This needs to be fixed by adding `#ifndef RC_INVOKED` sections to header
files included by the .rc files.

Other notes:

- PCH is currently disabled because Clang prints this warning:
  error: GNU extensions was enabled in precompiled file 'cmake_pch.pch' but is currently disabled

- RapidJSON: Returning a Value fails:
  error : calling a private constructor of class 'rapidjson::GenericValue<rapidjson::UTF8<>>'
  extlib\rapidjson\include\rapidjson/document.h(578,5): note: declared private here

  Workaround: Use a Value& as an out reference parameter.

- ClangCL with MSVC 2026 uses a path that doesn't define libintl_textdomain.
  so for DelayLoad test functions, use textdomain and some macros to define
  the libintl_textdomain version for compatibility.