[lz4] CMakeLists.txt: Only set the dllexport/dllimport flags on Windows.
This broke the Mac OS X build:

In file included from /Users/travis/build/GerbilSoft/rom-properties/extlib/lz4/lib/lz4.c:110:

/Users/travis/build/GerbilSoft/rom-properties/extlib/lz4/contrib/cmake_unofficial/../../lib/lz4.h:119:1: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes

LZ4LIB_API int LZ4LIB_CALL LZ4_versionNumber (void);  /**< library version number; useful to check dll version */

^

/Users/travis/build/GerbilSoft/rom-properties/extlib/lz4/contrib/cmake_unofficial/../../lib/lz4.h:100:22: note: expanded from macro 'LZ4LIB_API'

.#  define LZ4LIB_API __declspec(dllexport) LZ4LIB_VISIBILITY

                     ^