FIND_PACKAGE(Threads REQUIRED) and add CMAKE_THREAD_LIBS_INIT in anything that uses std::call_once().
Fixes a linker error on Xubuntu 16.04, and other older distros that
no longer have a separate libdl (glibc-2.34):

/usr/bin/ld: ../../../lib/../src/libgsvt/CMakeFiles/gsvt.dir/gsvt_posix.c.o: undefined reference to symbol 'pthread_once@@GLIBC_2.0'
//lib/i386-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/libromdata/tests/CMakeFiles/WiiUFstPrint.dir/build.make:124: recipe for target 'bin/WiiUFstPrint' failed
make[2]: *** [bin/WiiUFstPrint] Error 1
CMakeFiles/Makefile2:3963: recipe for target 'src/libromdata/tests/CMakeFiles/WiiUFstPrint.dir/all' failed
make[1]: *** [src/libromdata/tests/CMakeFiles/WiiUFstPrint.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2