[librptexture] ImageDecoder_Linear_neon.cpp: Missing braces.
This broke the MSVC 2022 arm64 build:

src\librptexture\decoder\ImageDecoder_Linear_neon.cpp(176,3): error C2360: initialization of 'shuf_mask_Swap_ARGB32' is skipped by 'case' label
src\librptexture\decoder\ImageDecoder_Linear_neon.cpp(169,36): message : see declaration of 'shuf_mask_Swap_ARGB32'
src\librptexture\decoder\ImageDecoder_Linear_neon.cpp(177,3): error C2360: initialization of 'shuf_mask_Swap_ARGB32' is skipped by 'case' label
src\librptexture\decoder\ImageDecoder_Linear_neon.cpp(169,36): message : see declaration of 'shuf_mask_Swap_ARGB32'
src\librptexture\decoder\ImageDecoder_Linear_neon.cpp(187,3): error C2360: initialization of 'shuf_mask_Swap_ARGB32' is skipped by 'case' label
src\librptexture\decoder\ImageDecoder_Linear_neon.cpp(169,36): message : see declaration of 'shuf_mask_Swap_ARGB32'
src\librptexture\decoder\ImageDecoder_Linear_neon.cpp(199,3): error C2360: initialization of 'shuf_mask_Swap_ARGB32' is skipped by 'case' label
src\librptexture\decoder\ImageDecoder_Linear_neon.cpp(169,36): message : see declaration of 'shuf_mask_Swap_ARGB32'
src\librptexture\decoder\ImageDecoder_Linear_neon.cpp(208,3): error C2361: initialization of 'shuf_mask_Swap_ARGB32' is skipped by 'default' label
src\librptexture\decoder\ImageDecoder_Linear_neon.cpp(169,36): message : see declaration of 'shuf_mask_Swap_ARGB32'

Not sure why gcc seemingly didn't care...