[librptext] conversion_iconv.cpp, T_cpN_to_unicode(): Fix the UTF-16 code path on clang-21.
Testing with Termux on Android, this fails:

src/librptext/conversion_iconv.cpp:306:10: error: assignment to cast is illegal, lvalue casts are not supported
  306 |                                         if ((uint16_t)*p = 0x301C) {
      |                                             ^~~~~~~~~~~~ ~

Note the single equals sign. This would have broken anything that
used this code path.

Also, since we're only using one code point from *p, cast it early
and store it in a uint16_t variable.

This fixes a regression from commit c449f74e189776981c0eb8d7b6b389826814b297.
([librptext] conversion_iconv.cpp, T_cpN_to_unicode<>(): Handle libiconv cp932 quirks for UTF-16.)