[libromdata] ISOPrivate: Fix initialization ordering in the constructor.
src/libromdata/Media/ISO.cpp: In constructor ‘LibRomData::ISOPrivate::ISOPrivate(const LibRpFile::IRpFilePtr&)’:
src/libromdata/Media/ISO.cpp:98:22: error: ‘LibRomData::ISOPrivate::sector_offset’ will be initialized after [-Werror=reorder]
   98 |         unsigned int sector_offset;
      |                      ^~~~~~~~~~~~~
src/libromdata/Media/ISO.cpp:91:23: error:   ‘LibRomData::ISOPrivate::JolietSVDType LibRomData::ISOPrivate::jolietSVDType’ [-Werror=reorder]
   91 |         JolietSVDType jolietSVDType;
      |                       ^~~~~~~~~~~~~
src/libromdata/Media/ISO.cpp:287:1: error:   when initialized here [-Werror=reorder]
  287 | ISOPrivate::ISOPrivate(const IRpFilePtr &file)
      | ^~~~~~~~~~
cc1plus: all warnings being treated as errors

This fixes a regression from commit eeaf1f24185f8cb418964c7a08e0e1b4df7c04e3.
(Reduce padding in some structs.)