[cmake] msvc.cmake: Disable "/permissive-" if the toolset ends in "_xp".
This is the actual cause of the IUnknown issue worked around in the
previous commit, since it seems CMake sets CMAKE_SYSTEM_VERSION to
10.0, even though MSVC 17.14.16 is using the Windows 7 SDK with the
v141_xp toolset.

Now we're checking for both CMAKE_SYSTEM_VERSION and a toolset that
doesn't end in "_xp".

This fixes a different issue caused by the older Gdiplus headers having
extraneous qualifiers:

c:\program files (x86)\microsoft sdks\windows\v7.1a\include\GdiplusHeaders.h(891):
error C4596: 'EmfToWmfBits': illegal qualified name in member declaration
(compiling source file src\libwin32darkmode\TGDarkMode.cpp)