[libcachecommon/tests] FilterCacheKeyTest, filterCacheKey_EINVAL: Explicitly cast nullptr to char*.
Otherwise, the Windows build fails due to ambiguous overloads:

  FilterCacheKeyTest.cpp
src\libcachecommon\tests\FilterCacheKeyTest.cpp(240): error C2668: 'LibCacheCommon::filterCacheKey': ambiguous call to overloaded function [build\src\libcachecommon\tests\FilterCacheKeyTest.vcxproj]
  src\libcachecommon\tests\../CacheKeys.hpp(65): note: could be 'int LibCacheCommon::filterCacheKey(std::wstring &)'
  src\libcachecommon\tests\../CacheKeys.hpp(57): note: or       'int LibCacheCommon::filterCacheKey(wchar_t *)'
  src\libcachecommon\tests\../CacheKeys.hpp(43): note: or       'int LibCacheCommon::filterCacheKey(std::string &)'
  src\libcachecommon\tests\../CacheKeys.hpp(26): note: or       'int LibCacheCommon::filterCacheKey(char *)'
  src\libcachecommon\tests\FilterCacheKeyTest.cpp(240): note: while trying to match the argument list '(nullptr)'