[librpbase] ImageDecoder_BC7: Need to enable SSSE3 before including tmmintrin.h.
gcc-4.8 on travis-ci complained about this:

In file included from /home/travis/build/GerbilSoft/rom-properties/src/librpbase/img/ImageDecoder_BC7.cpp:39:0:
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/tmmintrin.h:31:3: error: #error "SSSE3 instruction set not enabled"
.# error "SSSE3 instruction set not enabled"
   ^