[gtk] Add missing #includes where necessary.
These broke on Ubuntu 16.04 (i386). (I'm guessing these headers are
somehow indirectly included on later systems...)

src/gtk/is-supported.cpp: In function ‘LibRpBase::RomDataPtr rp_gtk_open_uri(const char*)’:
src/gtk/is-supported.cpp:41:18: error: ‘R_OK’ was not declared in this scope
  if (access(uri, R_OK) == 0) {
                  ^
src/gtk/is-supported.cpp:41:22: error: ‘access’ was not declared in this scope
  if (access(uri, R_OK) == 0) {
                      ^

src/gtk/gtk3/MenuProviderCommon.c: In function ‘rp_menu_provider_convert_to_png’:
src/gtk/gtk3/MenuProviderCommon.c:59:28: error: implicit declaration of function ‘strlen’ [-Werror=implicit-function-declaration]
  const size_t source_len = strlen(source_uri);
                            ^
src/gtk/gtk3/MenuProviderCommon.c:59:28: warning: incompatible implicit declaration of built-in function ‘strlen’
src/gtk/gtk3/MenuProviderCommon.c:59:28: note: include ‘<string.h>’ or provide a declaration of ‘strlen’
src/gtk/gtk3/MenuProviderCommon.c:71:24: error: implicit declaration of function ‘strrchr’ [-Werror=implicit-function-declaration]
  gchar *const dotpos = strrchr(output_file_esc, '.');
                        ^
src/gtk/gtk3/MenuProviderCommon.c:71:24: warning: incompatible implicit declaration of built-in function ‘strrchr’
src/gtk/gtk3/MenuProviderCommon.c:71:24: note: include ‘<string.h>’ or provide a declaration of ‘strrchr’
src/gtk/gtk3/MenuProviderCommon.c:81:4: error: implicit declaration of function ‘strcpy’ [-Werror=implicit-function-declaration]
    strcpy(dotpos, ".png");
    ^
src/gtk/gtk3/MenuProviderCommon.c:81:4: warning: incompatible implicit declaration of built-in function ‘strcpy’
src/gtk/gtk3/MenuProviderCommon.c:81:4: note: include ‘<string.h>’ or provide a declaration of ‘strcpy’
src/gtk/gtk3/MenuProviderCommon.c: In function ‘mime_type_compar’:
src/gtk/gtk3/MenuProviderCommon.c:113:9: error: implicit declaration of function ‘strcmp’ [-Werror=implicit-function-declaration]
  return strcmp(sa, sb);
         ^