Fix underlinking in the GTK UI frontends.
Add the following linker options:
- --no-undefined
- --no-allow-shlib-undefined

GTK UI frontends: Link to Pango, GDK, and other libraries directly if
we're using symbols from those libraries.

NOTE: CMake's FindGTK2 seems to do this already, but we'll add the extra
linking ourselves just in case.

This fixes errors similar to the following after adding the
linker options:

/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../x86_64-pc-linux-gnu/bin/ld:
	src/gtk/gtk3/CMakeFiles/rom-properties-gtk3.dir/__/config/CacheTab.cpp.o:
	undefined reference to symbol 'gdk_window_set_cursor'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../x86_64-pc-linux-gnu/bin/ld:
	/usr/lib64/libgdk-3.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status