A few more ANSI Windows build fixes.
rom-properties still won't build for ANSI Windows, but these were
simple fixes.

tcharx.h: Move `#define sntprintf swprintf` into the `#ifdef _UNICODE`
block.

[librpfile] RpFile_win32.cpp, RpFilePrivate::reOpenFile(): Fix the ANSI
build for GetDriveType().

[librpfile] FileSystem_win32.cpp, GetFileAttributes_ovl():
- Take LPCWSTR instead of LPCTSTR.
- Rename to GetFileAttributes_wrapper().

[libgsvt] gsvt.c: +#include <stdlib.h> for getenv().
Wasn't needed for _tgetenv(), but *is* needed for the ANSI version.

src/libgsvt/gsvt.c: In function ‘gsvt_check_graphics_protocol_support’:
src/libgsvt/gsvt.c:47:27: error: implicit declaration of function ‘getenv’ [-Wimplicit-function-declaration]
   47 |         supports_sixel = (_tgetenv(_T("WT_SESSION")) != NULL);
      |                           ^~~~~~~~
src/libgsvt/gsvt.c:19:1: note: ‘getenv’ is defined in header ‘<stdlib.h>’; this is probably fixable by adding ‘#include <stdlib.h>’
   18 | #include "ctypex.h"
  +++ |+#include <stdlib.h>
   19 |

[win32] RP_ExtractImage_Private::Fallback(): Use TCHAR for filetype_key.

[win32] KeyManagerTabPrivate::showKeyImportReturnStatus():
- Use _tcserror() instead of _wcserror().