[win32] RP_XAttrView::Initialize(): Move the hr/tfilename variable block to before `goto cleanup;`.
MSVC complains that tfilename might not be initialized:

src\win32\rp_xattrview.cpp(401): error C4703: potentially uninitialized
local pointer variable 'tfilename' used

This, and the previous commit for `fe`, are likely regressions from
commit 7f17b78d132c6e2a1ad3de6d99b96e28903e1e5f.
([librptexture] DirectDrawSurface: Detect BC4S and BC5S, but disable SNORM/SINT decoding.)

...because I accidentally committed the XAttrView enable check in this
commit. It should still work, but rp-config on Windows hasn't been
updated to support it yet.