[libromdata] iQuePlayer: FIXME: False-positive error on Ubuntu 22.04 arm64 due to the use of unz_size/2.
In function ‘fromLinear16’,
    inlined from ‘loadImage’ at ./src/libromdata/Console/iQuePlayer.cpp:314:32:
./src/libromdata/../librptexture/decoder/ImageDecoder_Linear.hpp:135:77: error: ‘fromLinear16_cpp’ reading 12544 bytes from a region of size 8832 [-Werror=stringop-overread]
./src/libromdata/../librptexture/decoder/ImageDecoder_Linear.hpp: In member function ‘loadImage’:
./src/libromdata/../aligned_malloc.h:68:22: note: source object of size [6272, 8832] allocated by ‘aligned_alloc’
../librptexture/./src/librptexture/decoder/ImageDecoder_Linear.cpp:717:14: note: in a call to function ‘fromLinear16_cpp’ declared with attribute ‘access (read_only, 4, 5)’
lto1: all warnings being treated as errors
make[4]: *** [/tmp/ccktAlyL.mk:14: /tmp/cc86M3xK.ltrans4.ltrans.o] Error 1
make[4]: *** Waiting for unfinished jobs....
lto-wrapper: fatal error: make returned 2 exit status

TODO: Figure out how to fix this without simply suppressing the warning.

Also, this only happens on arm64. armhf and amd64 don't have this.