[fmt] format.h: Backport a fix for uint128 bitwise not.
Fixes breakage on Ubuntu 16.04 (i386):

In file included from extlib/fmt/include/fmt/format-inl.h:28:0,
                 from extlib/fmt/src/format.cc:8:
extlib/fmt/include/fmt/format.h: In instantiation of ‘void fmt::v12::detail::format_hexfloat(Float, fmt::v12::format_specs, fmt::v12::detail::buffer<char>&) [with Float = long double; typename std::enable_if<(! std::integral_constant<bool, (std::numeric_limits<_Tp>::digits == 106)>::value), int>::type <anonymous> = 0]’:
extlib/fmt/include/fmt/format.h:3504:20:   required from ‘OutputIt fmt::v12::detail::write(OutputIt, T, fmt::v12::format_specs, fmt::v12::locale_ref) [with Char = char; OutputIt = fmt::v12::basic_appender<char>; T = long double; typename std::enable_if<(fmt::v12::detail::is_floating_point<T>::value), int>::type <anonymous> = 0]’
extlib/fmt/include/fmt/format.h:3598:21:   required from ‘OutputIt fmt::v12::detail::write(OutputIt, T) [with Char = char; OutputIt = fmt::v12::basic_appender<char>; T = long double; typename std::enable_if<(fmt::v12::detail::is_floating_point<T>::value && (! fmt::v12::detail::is_fast_float<T>::value)), int>::type <anonymous> = 0]’
extlib/fmt/include/fmt/format.h:3688:16:   required from ‘void fmt::v12::detail::default_arg_formatter<Char>::operator()(T) [with T = long double; typename std::enable_if<(std::integral_constant<bool, (std::is_same<T, int>::value || 1)>::value), int>::type <anonymous> = 0; Char = char]’
extlib/fmt/include/fmt/base.h:2505:52:   required from ‘decltype (vis(0)) fmt::v12::basic_format_arg<Context>::visit(Visitor&&) const [with Visitor = fmt::v12::detail::default_arg_formatter<char>; Context = fmt::v12::context; decltype (vis(0)) = void]’
extlib/fmt/include/fmt/format-inl.h:1471:62:   required from here
extlib/fmt/include/fmt/format.h:3111:14: error: no match for ‘operator~’ (operand type is ‘fmt::v12::detail::uint128’)
       f.f &= ~(inc - 1);
              ^
extlib/fmt/include/fmt/format.h:1714:20: error: ‘OutputIt fmt::v12::detail::write_padded(OutputIt, const fmt::v12::format_specs&, size_t, size_t, F&&) [with Char = char; fmt::v12::align default_align = (fmt::v12::align)1; OutputIt = fmt::v12::basic_appender<char>; F = fmt::v12::detail::write_char(OutputIt, Char, const fmt::v12::format_specs&) [with Char = char; OutputIt = fmt::v12::basic_appender<char>]::<lambda(fmt::v12::detail::reserve_iterator<fmt::v12::basic_appender<char> >)>&; size_t = unsigned int]’, declared using local type ‘fmt::v12::detail::write_char(OutputIt, Char, const fmt::v12::format_specs&) [with Char = char; OutputIt = fmt::v12::basic_appender<char>]::<lambda(fmt::v12::detail::reserve_iterator<fmt::v12::basic_appender<char> >)>’, is used but never defined [-fpermissive]
 FMT_CONSTEXPR auto write_padded(OutputIt out, const format_specs& specs,
                    ^
extlib/fmt/include/fmt/format.h:1714:20: error: ‘OutputIt fmt::v12::detail::write_padded(OutputIt, const fmt::v12::format_specs&, size_t, size_t, F&&) [with Char = char; fmt::v12::align default_align = (fmt::v12::align)2; OutputIt = fmt::v12::basic_appender<char>; F = fmt::v12::detail::write_bytes(OutputIt, fmt::v12::string_view, const fmt::v12::format_specs&) [with Char = char; fmt::v12::align default_align = (fmt::v12::align)2; OutputIt = fmt::v12::basic_appender<char>; fmt::v12::string_view = fmt::v12::basic_string_view<char>]::<lambda(fmt::v12::detail::reserve_iterator<fmt::v12::basic_appender<char> >)>&; size_t = unsigned int]’, declared using local type ‘fmt::v12::detail::write_bytes(OutputIt, fmt::v12::string_view, const fmt::v12::format_specs&) [with Char = char; fmt::v12::align default_align = (fmt::v12::align)2; OutputIt = fmt::v12::basic_appender<char>; fmt::v12::string_view = fmt::v12::basic_string_view<char>]::<lambda(fmt::v12::detail::reserve_iterator<fmt::v12::basic_appender<char> >)>’, is used but never defined [-fpermissive]