[libwin32darkmode] IatHook.hpp: Explicitly cast import->Name to const char*.
This failed in the AppVeyor build with MSVC 2015:

src\libwin32darkmode\IatHook.hpp(35): error C2664: 'int strcmp(const char *,const char *)':
cannot convert argument 1 from 'BYTE [1]' to 'const char *'
(compiling source file src\libwin32darkmode\DarkMode.cpp)

src\libwin32darkmode\IatHook.hpp(35): note: Types pointed to are unrelated;
conversion requires reinterpret_cast, C-style cast or function-style cast
(compiling source file src\libwin32darkmode\DarkMode.cpp)