[kde] LanguageComboBox.hpp: #include "common.h" for ATTR_ACCESS_SIZE().
This didn't cause a problem when building locally, but it broke on
travis-ci with Ubuntu 14.04:

[ 73%] Building CXX object src/kde/kde4/CMakeFiles/rom-properties-kde4.dir/rom-properties-kde4_automoc.cpp.o
In file included from /home/travis/build/GerbilSoft/rom-properties/build/src/kde/kde4/moc_LanguageComboBox.cpp:9:0,
                 from /home/travis/build/GerbilSoft/rom-properties/build/src/kde/kde4/rom-properties-kde4_automoc.cpp:11:
/home/travis/build/GerbilSoft/rom-properties/build/src/kde/kde4/../../../../src/kde/LanguageComboBox.hpp:52:20: error: ‘read_only’ has not been declared
   ATTR_ACCESS_SIZE(read_only, 2, 3)
                    ^
/home/travis/build/GerbilSoft/rom-properties/build/src/kde/kde4/../../../../src/kde/LanguageComboBox.hpp:52:31: error: expected identifier before numeric constant
   ATTR_ACCESS_SIZE(read_only, 2, 3)
                               ^
/home/travis/build/GerbilSoft/rom-properties/build/src/kde/kde4/../../../../src/kde/LanguageComboBox.hpp:52:31: error: expected ‘,’ or ‘...’ before numeric constant
/home/travis/build/GerbilSoft/rom-properties/build/src/kde/kde4/../../../../src/kde/LanguageComboBox.hpp:52:35: error: ISO C++ forbids declaration of ‘ATTR_ACCESS_SIZE’ with no type [-fpermissive]
   ATTR_ACCESS_SIZE(read_only, 2, 3)
                                   ^
/home/travis/build/GerbilSoft/rom-properties/build/src/kde/kde4/../../../../src/kde/LanguageComboBox.hpp:52:35: error: expected ‘;’ at end of member declaration
make[2]: *** [src/kde/kde4/CMakeFiles/rom-properties-kde4.dir/rom-properties-kde4_automoc.cpp.o] Error 1