[gtk] CMakeLists.txt: Move the rom-properties-glib GLib version macros to after GTK4 is checked.
Otherwise, if BUILD_GTK4 is set but GTK4 isn't actually present, and the
system has glib <2.66, an error occurs:

In file included from /usr/include/glib-2.0/glib/gtypes.h:34,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from build/src/gtk/NetworkManager.h:11,
                 from build/src/gtk/NetworkManager.c:12:
/usr/include/glib-2.0/glib/gversionmacros.h:271:2: error: #error "GLIB_VERSION_MIN_REQUIRED must be <= GLIB_VERSION_CUR_STABLE"
  271 | #error "GLIB_VERSION_MIN_REQUIRED must be <= GLIB_VERSION_CUR_STABLE"
      |  ^~~~~
/usr/include/glib-2.0/glib/gversionmacros.h:274:2: error: #error "GLIB_VERSION_MAX_ALLOWED must be >= GLIB_VERSION_MIN_REQUIRED"
  274 | #error "GLIB_VERSION_MAX_ALLOWED must be >= GLIB_VERSION_MIN_REQUIRED"
      |  ^~~~~

This should fix the AppVeyor build.