[librpbase, libromdata, rpcli] Put the char8_t/u8string operator<<() functions in stdafx.h.
The Linux build was fine, but the MSVC build failed due to usage in
Xbox360_XEX and Xbox_XBE, which were previously using u8ostringstream:

src\libromdata\Console\Xbox360_XEX.cpp(1805,9): error C2280: 'std::basic_ostream<char,std::char_traits<char>> &std::operator <<
<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const char8_t *)': attempting to reference a deleted function
src\libromdata\Console\Xbox360_XEX.cpp(1805,9): error C2088: '<<': illegal for class
src\libromdata\Console\Xbox_XBE.cpp(808,7): error C2280: 'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std
::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const char8_t *)': attempting to reference a deleted function
src\libromdata\Console\Xbox_XBE.cpp(808,7): error C2088: '<<': illegal for class