[libromdata] EXEPrivate::loadNEResident(): Change set_span's offset parameter from `auto` to `unsigned int`.
uint16_t could probably work here, but unsigned int is faster on
modern x86.

gcc-5 (Xubuntu 16.04) doesn't allow auto as a lambda parameter:
EXE_NE.cpp:65:56: error: use of ‘auto’ in lambda parameter declaration
	only available with -std=c++14 or -std=gnu++14

gcc-12.2 does, since as of gcc-11, it defaults to C++ 2017.