[librptexture] ValveVTFPrivate::getMipmapInfo(): Need to return a value...
src/librptexture/fileformat/ValveVTF.cpp: In member function ‘int LibRpTexture::ValveVTFPrivate::getMipmapInfo()’:
src/librptexture/fileformat/ValveVTF.cpp:334:3: error: return-statement with no value, in function returning ‘int’ [-fpermissive]
  334 |   return;
      |   ^~~~~~

This was on the PowerVR branch, but it didn't cause any compile errors
there, even though it definitely should have...

This fixes a build regression from commit a6ef730959ad0c5b2830d582cd45535b6aeae79f.
([librptexture] ValveVTF: Limit to 128 mipmaps.)