[librpbase] JSONROMOutput: Remove the `lc` parameter.
It's not used for JSON output, since the JSON output has *all* of the
localized strings for RFT_STRING_MULTI fields (and multi-language
RFT_LISTDATA fields).

Fixes this clang warning:

In file included from src/librpbase/TextOut_json.cpp:11:
src/librpbase/TextOut.hpp:52:11: error: private field 'lc' is not used [-Werror,-Wunused-private-field]
   52 |         uint32_t lc;
      |                  ^
1 error generated.