[libwin32ui] LoadResource_i18n(): Don't capture `lc` in the std::lower_bound() comparator lambda.
`lc` is passed to std::lower_bound() and is used as needed anyway,
so there's no need for it to be captured.

Interestingly, MSVC didn't complain about this, but gcc-13.2.0 did:

src/libwin32ui/LoadResource_i18n.cpp: In lambda function:
src/libwin32ui/LoadResource_i18n.cpp:61:70: error: lambda parameter ‘lc’ previously declared as a capture
   61 |                         [lc](const lc_mapping_t lc_mapping, uint32_t lc) {
      |                                                             ~~~~~~~~~^~

This, combined with the previous few commits, fixes the MinGW-w64 build.
I'm still not officially supporting it due to the lack of automatic
activation contexts for COM controls, though... (.inl stuff)