[librpbase] cpu_dispatch.h: Disable IFUNC in clang builds for now.
travis-ci upgraded from clang-3.5.0 to clang-3.9.0. clang-3.9.0 supports
IFUNC, but it isn't working here:

src/librpbase/img/ImageDecoder_ifunc.cpp:92:25: error:
      out-of-line declaration of a member must be a definition
      [-Wout-of-line-declaration]
rp_image *ImageDecoder::fromLinear24(PixelFormat px_format,
          ~~~~~~~~~~~~~~^