arm_neon_aligned.h: Add vld1q_u8_x3() and vst1q_u8_x3().
These are needed for Ubuntu 16.04 arm64:

/<<PKGBUILDDIR>>/src/librptexture/decoder/ImageDecoder_Linear_neon24.cpp: In function ‘LibRpTexture::rp_image_ptr LibRpTexture::ImageDecoder::fromLinear24_neon(LibRpTexture::ImageDecoder::PixelFormat, int, int, const uint8_t*, size_t, int)’:
/<<PKGBUILDDIR>>/src/librptexture/decoder/ImageDecoder_Linear_neon24.cpp:129:42: error: ‘vld1q_u8_x3’ was not declared in this scope
    uint8x16x3_t rgb = vld1q_u8_x3(img_buf);

(cherry picked from commit 50b778d9a0e298d8454d4035f46a442ab8b3ebdd)