[libromdata] WiiUData: Fix sorting issues.
This caused asserts when using libstdc++ debug mode.

wiiu_application_types: "Game Update" should be after "Game DLC".
This broke "Super Smash Bros. for Wii U (USA) (Update)".

/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/stl_algo.h:1970:
In function:
    _FIter std::lower_bound(_FIter, _FIter, const _Tp&, _Compare) [with
    _FIter = const LibRomData::WiiUData::WiiUApplicationType*; _Tp =
    unsigned int; _Compare =
    LibRomData::WiiUData::lookup_application_type(uint32_t)::<lambda(const
    LibRomData::WiiUData::WiiUApplicationType&, uint32_t)>]

Error: elements in iterator range [first, last) are not partitioned by the
predicate __comp and value __val.

Objects involved in the operation:
    iterator "first" @ 0x7fffffffc578 {
      type = LibRomData::WiiUData::WiiUApplicationType const* (constant iterator);
    }
    iterator "last" @ 0x7fffffffc570 {
      type = LibRomData::WiiUData::WiiUApplicationType const* (constant iterator);
    }

disc_publishers_noregion: Three disc publishers were out of order.
This broke "NES REMIX (USA)" and "NES REMIX 2 (USA)".

/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/stl_algo.h:1970:
In function:
    _FIter std::lower_bound(_FIter, _FIter, const _Tp&, _Compare) [with
    _FIter = const LibRomData::WiiUData::WiiUDiscPublisher*; _Tp = unsigned
    int; _Compare = LibRomData::WiiUData::lookup_disc_publisher(const
    char*)::<lambda(const LibRomData::WiiUData::WiiUDiscPublisher&,
    uint32_t)>]

Error: elements in iterator range [first, last) are not partitioned by the
predicate __comp and value __val.

Objects involved in the operation:
    iterator "first" @ 0x7ffc13befb38 {
      type = LibRomData::WiiUData::WiiUDiscPublisher const* (constant iterator);
    }
    iterator "last" @ 0x7ffc13befb30 {
      type = LibRomData::WiiUData::WiiUDiscPublisher const* (constant iterator);
    }