[libromdata/tests] FilterCacheKeyTest, filterCacheKey_EINVAL: Missing ')'.
src\libcachecommon\tests\FilterCacheKeyTest.cpp(240): fatal error C1057: unexpected end of file in macro expansion