[libwin32darkmode] DarkModeCtrl.hpp: #include <assert.h>, not <cassert>.
This file is included by svrplus.c, so we can't use C++ namespace headers.
Otherwise, we end up with a wacky error:

MSVC\14.36.32532\include\yvals_core.h(28): STL1003: Unexpected compiler, expected C++ compiler.
MSVC\14.36.32532\include\yvals_core.h(29,1): fatal  error C1189: #error:  Error in C++ Standard Library usage