[libptexture] ImageDecoder_Linear_neon16.cpp: vzip1q_u16() and vzip2q_u16() should return uint16x8_t, not uint32x4_t.
ARM gcc enforces strict vector conversions by default, whereas clang and
MSVC do not. These functions usually only exist on arm64, and they
normally return uint16x8_t, so we should handle it the same way here.
(The caller already has a vreinterpretq_u32_u16(), so this will
"just work.")

src/librptexture/decoder/ImageDecoder_Linear_neon16.cpp: In function ‘void LibRpTexture::ImageDecoder::T_RGB16_neon(uint16_t, uint16_t, uint16_t, const uint16_t*, uint32_t*)’:
src/librptexture/decoder/ImageDecoder_Linear_neon16.cpp:128:42: note: use ‘-flax-vector-conversions’ to permit conversions between vectors with differing element types or numbers of subparts
  128 |         px.val[0] = vreinterpretq_u32_u16(vzip1q_u16(sB, sR));
      |                     ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
src/librptexture/decoder/ImageDecoder_Linear_neon16.cpp:128:53: error: cannot convert ‘uint32x4_t’ to ‘uint16x8_t’
  128 |         px.val[0] = vreinterpretq_u32_u16(vzip1q_u16(sB, sR));
      |                                           ~~~~~~~~~~^~~~~~~~
      |                                                     |
      |                                                     uint32x4_t