[debian] control: Add libfmt-dev.
This should've been added for Ubuntu 20.04 "Noble" Numbat, which has
libfmt-8.1.1, but I forgot to add it.

With 22.04, there's a weird compile error:

In file included from /<<PKGBUILDDIR>>/src/kde/kf5/../stdafx.h:35,
                 from /<<PKGBUILDDIR>>/src/kde/kf5/ThumbnailCreatorPluginFactoryKF5.cpp:17:
/<<PKGBUILDDIR>>/src/kde/kf5/../../rp-libfmt.h:14:10: fatal error: fmt/format.h: No such file or directory
   14 | #include <fmt/format.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.

TODO: Fix this later.