[librptext] conversion.cpp: #include "common.h" for unlikely().
This only broke on the Ubuntu 16.04 armhf build for some reason...

/<<PKGBUILDDIR>>/src/librptext/conversion.cpp: In function ‘void LibRpText::trimEnd(char*)’:
/<<PKGBUILDDIR>>/src/librptext/conversion.cpp:153:37: error: ‘unlikely’ was not declared in this scope
  if (unlikely(!str || str[0] == '\0'))
                                     ^

(cherry picked from commit c9a657bfa945212fa8656cb6f5a8ed2872ff8f3c)