[xfce] CMakeLists.txt: Link in CMAKE_DL_LIBS if needed.
glibc-2.34 folded libdl and other libraries into libc.
On older systems, we still need -ldl.

This should fix the AppVeyor Ubuntu build, which uses Ubuntu 18.04
(glibc-2.27):

/usr/bin/ld: src/gtk/xfce/CMakeFiles/rom-properties-xfce.dir/__/gtk3/RpThunarPlugin.cpp.o:
	undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line