[gettext] intl-exports.c: Use __asm() instead of asm().
asm() is a GNU C extension, and GNU extensions were disabled in
commit 398f79c751acc01e105767900d05e3de2d75eebf.
(Disable C/C++ extensions.)

This fixes the following errors when building with MinGW-w64:

In file included from extlib/gettext/gettext-runtime/intl/osdep.c:20:
extlib/gettext/gettext-runtime/intl/intl-exports.c:32:7: error: expected declaration specifiers or ‘...’ before string constant
   32 |  asm (".section .drectve\n");                                           \
      |       ^~~~~~~~~~~~~~~~~~~~~
extlib/gettext/gettext-runtime/intl/intl-exports.c:39:1: note: in expansion of macro ‘VARIABLE’
   39 | VARIABLE(libintl_version)
      | ^~~~~~~~
extlib/gettext/gettext-runtime/intl/intl-exports.c:33:7: error: expected declaration specifiers or ‘...’ before string constant
   33 |  asm (".ascii \" -export:" #x ",data\"\n");                             \
      |       ^~~~~~~~~~~~~~~~~~~~
extlib/gettext/gettext-runtime/intl/intl-exports.c:39:1: note: in expansion of macro ‘VARIABLE’
   39 | VARIABLE(libintl_version)
      | ^~~~~~~~
extlib/gettext/gettext-runtime/intl/intl-exports.c:34:7: error: expected declaration specifiers or ‘...’ before string constant
   34 |  asm (".data\n");                                                       \
      |       ^~~~~~~~~
extlib/gettext/gettext-runtime/intl/intl-exports.c:39:1: note: in expansion of macro ‘VARIABLE’
   39 | VARIABLE(libintl_version)
      | ^~~~~~~~