[libwin32common] IOwnerDataCallback: Move the GUID to a .c file.
It needs to not be marked as static in order to build properly with
MSVC 2015 on AppVeyor:

  KeyManagerTab.cpp
C:\projects\rom-properties\src\win32\config\KeyManagerTab.cpp(43): error C2970: '_com_IIID': template parameter '_IID': 'IID_IOwnerDataCallback': an expression involving objects with internal linkage cannot be used as a non-type argument [C:\projects\rom-properties\build\src\win32\rom-properties.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\comip.h(40): note: see declaration of '_com_IIID'
  C:\projects\rom-properties\src\libwin32common/sdk/IOwnerDataCallback.hpp(20): note: see declaration of 'IID_IOwnerDataCallback'

Interestingly, it worked just fine with MSVC 2026 and 2017...