[kde] ITab.hpp: Revert the `#include <QSettings>` -> `class QSettings;` change.
This seemingly works fine on Qt4 and Qt6, but it causes QMetaType
breakage on Qt5:

In file included from /usr/include/i386-linux-gnu/qt5/QtCore/qtimer.h:37:0,
                 from /usr/include/i386-linux-gnu/qt5/QtCore/QTimer:1,
                 from /home/david/p/rom-properties/build/src/kde/kf5/../../../../src/kde/DragImageLabel.hpp:23,
                 from /home/david/p/rom-properties/build/src/kde/kf5/moc_DragImageLabel.cpp:9,
                 from /home/david/p/rom-properties/build/src/kde/kf5/rom-properties-kf5_LIB_automoc.cpp:2:
/usr/include/i386-linux-gnu/qt5/QtCore/qmetatype.h: In instantiation of ‘struct QtPrivate::IsPointerToTypeDerivedFromQObject<QSettings*>’:
/usr/include/i386-linux-gnu/qt5/QtCore/qmetatype.h:1565:60:   required from ‘struct QMetaTypeId<QSettings*>’
/usr/include/i386-linux-gnu/qt5/QtCore/qmetatype.h:1583:10:   required from ‘struct QMetaTypeId2<QSettings*>’
/usr/include/i386-linux-gnu/qt5/QtCore/qmetatype.h:1659:77:   required by substitution of ‘template<class T> int qRegisterMetaType(const char*, T*, typename QtPrivate::MetaTypeDefinedHelper<T, (QMetaTypeId2<T>::Defined && (! QMetaTypeId2<T>::IsBuiltIn))>::DefinedType) [with T = QSettings*]’
/home/david/p/rom-properties/build/src/kde/kf5/moc_AboutTab.cpp:97:82:   required from here
/usr/include/i386-linux-gnu/qt5/QtCore/qmetatype.h:1356:9: error: invalid application of ‘sizeof’ to incomplete type ‘QSettings’
         Q_STATIC_ASSERT_X(sizeof(T), "Type argument of Q_DECLARE_METATYPE(T*) must be fully defined");
         ^
/usr/include/i386-linux-gnu/qt5/QtCore/qmetatype.h: In instantiation of ‘constexpr int qMetaTypeId() [with T = QSettings*]’:
/usr/include/i386-linux-gnu/qt5/QtCore/qmetatype.h:1732:26:   required from ‘constexpr int qRegisterMetaType() [with T = QSettings*]’
/home/david/p/rom-properties/build/src/kde/kf5/moc_AboutTab.cpp:97:82:   required from here
/usr/include/i386-linux-gnu/qt5/QtCore/qmetatype.h:1725:5: error: static assertion failed: Type is not registered, please use the Q_DECLARE_METATYPE macro to make it known to Qt's meta-object system
     Q_STATIC_ASSERT_X(QMetaTypeId2<T>::Defined, "Type is not registered, please use the Q_DECLARE_METATYPE macro to make it
     ^

This partially reverts commit e452ecfef7d81fe127c5ed8c4e36c63f6dd41ca7.
(Remove even more unnecessary includes.)