[librpsecure] secoptions.c: ProcessExecuteFlags might be defined in an enum in newer versions of the Windows SDK and/or MinGW-w64.
Use a macro instead of an enum value to prevent build errors.

From AppVeyor on MinGW-w64 (32-bit):

C:\projects\rom-properties\src\librpsecure\win32\secoptions.c:43:2: error: redeclaration of enumerator 'ProcessExecuteFlags'
  ProcessExecuteFlags = 0x22,
  ^~~~~~~~~~~~~~~~~~~
In file included from C:\projects\rom-properties\src\librpsecure\win32\secoptions.c:22:0:
C:/mingw-w64/i686-6.3.0-posix-dwarf-rt_v5-rev1/mingw32/i686-w64-mingw32/include/winternl.h:873:5: note: previous definition of 'ProcessExecuteFlags' was here
     ProcessExecuteFlags,
     ^~~~~~~~~~~~~~~~~~~

(Interestingly, I can't seem to find this defined in the Windows SDK...)