[tests] Don't use `endl` in Google Test assertion messages.
Use `'\n'` instead.

This somehow breaks on 32-bit MSVC builds when using `/Gz`:

librpbase\tests\AesCipherTest.cpp(215): error C2678: binary '<<': no operator found which takes a left-hand operand of type 'testing::Message' (or there is no acceptable conversion)
libromdata\tests\CtrKeyScramblerTest.cpp(162): error C2678: binary '<<': no operator found which takes a left-hand operand of type 'testing::Message' (or there is no acceptable conversion)