FIXME: Some tests are failing on Launchpad on armhf/arm64.
Tests failing:
- ImageDecoderTest
- RomHeaderTest
- RomDataFormatTest_kf5

On armhf, RomDataFormatTest doesn't even compile due to a
truncation error:

/<<PKGBUILDDIR>>/src/kde/tests/RomDataFormatTest.cpp: In member function ‘virtual void LibRomData::Tests::RomDataFormatTest_formatDateTime_0_invalid_Test::TestBody()’:
/<<PKGBUILDDIR>>/src/kde/tests/RomDataFormatTest.cpp:72:3: error: narrowing conversion of ‘2147483648u’ from ‘unsigned int’ to ‘time_t {aka long int}’ inside { } [-Wnarrowing]
  }};
   ^
/<<PKGBUILDDIR>>/src/kde/tests/RomDataFormatTest.cpp: In member function ‘virtual void LibRomData::Tests::RomDataFormatTest_formatDateTime_1_dateOnly_Test::TestBody()’:
/<<PKGBUILDDIR>>/src/kde/tests/RomDataFormatTest.cpp:101:3: error: narrowing conversion of ‘2147483648u’ from ‘unsigned int’ to ‘time_t {aka long int}’ inside { } [-Wnarrowing]
  }};
   ^
/<<PKGBUILDDIR>>/src/kde/tests/RomDataFormatTest.cpp: In member function ‘virtual void LibRomData::Tests::RomDataFormatTest_formatDateTime_2_timeOnly_Test::TestBody()’:
/<<PKGBUILDDIR>>/src/kde/tests/RomDataFormatTest.cpp:125:3: error: narrowing conversion of ‘2147483648u’ from ‘unsigned int’ to ‘time_t {aka long int}’ inside { } [-Wnarrowing]
  }};
   ^
/<<PKGBUILDDIR>>/src/kde/tests/RomDataFormatTest.cpp: In member function ‘virtual void LibRomData::Tests::RomDataFormatTest_formatDateTime_3_dateAndTime_Test::TestBody()’:
/<<PKGBUILDDIR>>/src/kde/tests/RomDataFormatTest.cpp:150:3: error: narrowing conversion of ‘2147483648u’ from ‘unsigned int’ to ‘time_t {aka long int}’ inside { } [-Wnarrowing]
  }};
   ^
/<<PKGBUILDDIR>>/src/kde/tests/RomDataFormatTest.cpp: In member function ‘virtual void LibRomData::Tests::RomDataFormatTest_formatDateTime_4_invalid_Test::TestBody()’:
/<<PKGBUILDDIR>>/src/kde/tests/RomDataFormatTest.cpp:177:3: error: narrowing conversion of ‘2147483648u’ from ‘unsigned int’ to ‘time_t {aka long int}’ inside { } [-Wnarrowing]
  }};
   ^
/<<PKGBUILDDIR>>/src/kde/tests/RomDataFormatTest.cpp: In member function ‘virtual void LibRomData::Tests::RomDataFormatTest_formatDateTime_5_dateOnly_Test::TestBody()’:
/<<PKGBUILDDIR>>/src/kde/tests/RomDataFormatTest.cpp:207:3: error: narrowing conversion of ‘2147483648u’ from ‘unsigned int’ to ‘time_t {aka long int}’ inside { } [-Wnarrowing]
  }};
   ^
/<<PKGBUILDDIR>>/src/kde/tests/RomDataFormatTest.cpp: In member function ‘virtual void LibRomData::Tests::RomDataFormatTest_formatDateTime_6_timeOnly_noYear_Test::TestBody()’:
/<<PKGBUILDDIR>>/src/kde/tests/RomDataFormatTest.cpp:232:3: error: narrowing conversion of ‘2147483648u’ from ‘unsigned int’ to ‘time_t {aka long int}’ inside { } [-Wnarrowing]
  }};
   ^
/<<PKGBUILDDIR>>/src/kde/tests/RomDataFormatTest.cpp: In member function ‘virtual void LibRomData::Tests::RomDataFormatTest_formatDateTime_7_dateAndTime_noYear_Test::TestBody()’:
/<<PKGBUILDDIR>>/src/kde/tests/RomDataFormatTest.cpp:258:3: error: narrowing conversion of ‘2147483648u’ from ‘unsigned int’ to ‘time_t {aka long int}’ inside { } [-Wnarrowing]
  }};
   ^