[librpfile] RpFile_p.hpp: Disable ATTR_ACCESS_SIZE() for some of the SCSI functions for now.
scsi_read(): Passing pBuf (read_only) to scsi_send_cdb (which takes
read_write) causes a warning in the Release build:

src/librpfile/scsi/RpFile_scsi.cpp: In member function ‘int LibRpFile::RpFilePrivate::scsi_read(uint32_t, uint16_t, uint8_t*, size_t)’:
src/librpfile/scsi/RpFile_scsi.cpp:463:29: error: ‘pBuf’ may be used uninitialized [-Werror=maybe-uninitialized]
  463 |         return scsi_send_cdb(&cdb10, sizeof(cdb10), pBuf, req_buf_size, ScsiDirection::In);
      |                ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/librpfile/scsi/RpFile_scsi.cpp:427:77: note: accessing argument 4 of a function declared with attribute ‘access (write_only, 4, 5)’
  427 | int RpFilePrivate::scsi_read(uint32_t lbaStart, uint16_t lbaCount, uint8_t *pBuf, size_t bufLen)
      |                                                                    ~~~~~~~~~^~~~
cc1plus: all warnings being treated as errors