[librpbase] TextOut_text.cpp, formatDateTime(): Use localtime_r() instead of fmt::localtime().
Interestingly, this didn't print any warnings or errors on gcc, but on
MSVC, this warning was produced:

src\librpbase\TextOut_text.cpp(359,20): error C2220: the following warning is treated as an error
src\librpbase\TextOut_text.cpp(359,20): warning C4996: 'fmt::v11::localtime': was declared deprecated