[librptext] html_entities.h: #include <stddef.h> for size_t.
For some reason, 32-bit MSVC 2017 (v141_xp) builds fail due to size_t not
being defined, but 64-bit MSVC 2017 (v141_xp) builds work just fine...

This fixes the 32-bit MSVC 2017 (v141_xp) AppVeyor build:

c:\projects\rom-properties\src\librptext\html_entities.h(45): error C2061: syntax error: identifier 'rp_get_html_entities_table_count'
	(compiling source file C:\projects\rom-properties\src\librptext\html_entities.c)
c:\projects\rom-properties\src\librptext\html_entities.h(45): error C2059: syntax error: ';'
	(compiling source file C:\projects\rom-properties\src\librptext\html_entities.c)
c:\projects\rom-properties\src\librptext\html_entities.h(45): error C2059: syntax error: '<parameter-list>'
	(compiling source file C:\projects\rom-properties\src\librptext\html_entities.c)