[librptexture] PowerVR3.cpp: fmtLkup_tbl_U32[] now has 0 elements.
MSVC complained:

src\librptexture\fileformat\PowerVR3.cpp(196): error C2466: cannot
allocate an array of constant size 0

...but gcc did not. Weird.

fmtLkup_tbl_U32[] isn't used right now, so #if 0 it.

This fixes a regression from commit b050ffd8f7f94653fbdebe484e593c0415ef5d99.
(Various `for` loop changes, including more ranged `for` and int -> unsigned int.)