pthread_once_win32.h: Change `bool` to `unsigned char`.
This broke when compiling cpuflags_x86.c with MSVC 2015 on AppVeyor

Also #include "libwin32common/RpWin32_sdk.h" for SwitchToThread().

  cpuflags_x86.c
C:\projects\rom-properties\src\pthread_once_win32.h(32): error C2065: 'bool': undeclared identifier (compiling source file C:\projects\rom-properties\src\librpcpuid\cpuflags_x86.c)
C:\projects\rom-properties\src\pthread_once_win32.h(32): error C2146: syntax error: missing ';' before identifier 'run' (compiling source file C:\projects\rom-properties\src\librpcpuid\cpuflags_x86.c)
C:\projects\rom-properties\src\pthread_once_win32.h(32): error C2065: 'run': undeclared identifier (compiling source file C:\projects\rom-properties\src\librpcpuid\cpuflags_x86.c)
C:\projects\rom-properties\src\pthread_once_win32.h(32): error C2065: 'true': undeclared identifier (compiling source file C:\projects\rom-properties\src\librpcpuid\cpuflags_x86.c)
C:\projects\rom-properties\src\pthread_once_win32.h(33): error C2065: 'run': undeclared identifier (compiling source file C:\projects\rom-properties\src\librpcpuid\cpuflags_x86.c)
C:\projects\rom-properties\src\pthread_once_win32.h(44): error C2065: 'run': undeclared identifier (compiling source file C:\projects\rom-properties\src\librpcpuid\cpuflags_x86.c)
C:\projects\rom-properties\src\pthread_once_win32.h(44): error C2065: 'false': undeclared identifier (compiling source file C:\projects\rom-properties\src\librpcpuid\cpuflags_x86.c)
C:\projects\rom-properties\src\pthread_once_win32.h(48): error C2065: 'run': undeclared identifier (compiling source file C:\projects\rom-properties\src\librpcpuid\cpuflags_x86.c)
C:\projects\rom-properties\src\pthread_once_win32.h(48): error C2065: 'false': undeclared identifier (compiling source file C:\projects\rom-properties\src\librpcpuid\cpuflags_x86.c)
C:\projects\rom-properties\src\pthread_once_win32.h(52): error C4013: 'SwitchToThread' undefined; assuming extern returning int (compiling source file C:\projects\rom-properties\src\librpcpuid\cpuflags_x86.c)