[libromdata] GcnPartition: Remove a duplicated shift.
This was operating on an uninitialized variable, and it was effectively
useless because `size` is overwritten immediately after.

The AppVeyor build failed because of this:

gcnpartition.cpp(173): error C4700: uninitialized local variable 'size' used

This fixes a regression from commit f0673c19f821287e86de431b4ed5c52f6be5e636.
([libromdata] WiiPartition: Calculate the used partition size correctly for unencrypted RVT-H Reader disc images.)