[librptexture] PowerVR3Private::legacyPowerVRPixelFormatToPVR3(): Fix an off-by-one.
Needs to check for `>=`, not `>`. Otherwise, this can happen:

== Reading file 'id:000007,sig:06,src:015094,time:5391516,execs:1383460,op:flip2,pos:16'...
/usr/lib/gcc/x86_64-pc-linux-gnu/15/include/g++-v15/array:219:
In function:
    constexpr const std::array<_Tp, _Nm>::value_type& std::array<_Tp,
    _Nm>::operator[](size_type) const [with _Tp =
    LibRpTexture::PowerVR3Private::FmtLkup_t; long unsigned int _Nm = 32;
    const_reference = const LibRpTexture::PowerVR3Private::FmtLkup_t&;
    size_type = long unsigned int]

Error: attempt to subscript container with out-of-bounds index 32, but
container only holds 32 elements.

Objects involved in the operation:
    sequence "this" @ 0x7efc51dae960 {
      type = std::array<LibRpTexture::PowerVR3Private::FmtLkup_t, 32ul>;
    }
Aborted                    rpcli id\:000007*

Found using aflplusplus-4.21c.