[libwin32ui] LoadResource_i18n.cpp: Increase the lc_mappings size.
std::array<> doesn't have an implicit size, so this broke:

src\libwin32ui\LoadResource_i18n.cpp(55): error C2078: too many initializers