[libromdata] Nintendo3DSFirmData: pFirmBin -> &(*pFirmBin)
With the change from a C array to a C++ array, MSVC started to complain
about this (but gcc didn't care):

src\libromdata\data\Nintendo3DSFirmData.cpp(86,9): error C2440: 'return':
cannot convert from '_FwdIt' to 'const LibRomData::Nintendo3DSFirmData::FirmBin_t *'