[librptext] conversion.cpp, calc_frac_part(): Remove constexpr.
This is causing failures on MSVC 2015 on AppVeyor:

src\librptext\conversion.cpp(207): error C3250: 'frac_part': declaration is not allowed in 'constexpr' function body
src\librptext\conversion.cpp(217): error C3250: 'round_adj': declaration is not allowed in 'constexpr' function body
src\librptext\conversion.cpp(218): error C3249: illegal statement or sub-expression for 'constexpr' function
  src\librptext\conversion.cpp(218): note: see usage of '/='
src\librptext\conversion.cpp(219): error C3249: illegal statement or sub-expression for 'constexpr' function
  src\librptext\conversion.cpp(219): note: see usage of '+='
src\librptext\conversion.cpp(220): error C3256: 'frac_part': variable use does not produce a constant expression
src\librptext\conversion.cpp(204): error C3259: 'constexpr' functions can only have one return statement

This fixes a regression from commit a1fa5efedc94635d531f6a5f402230acbb9d5f62.
(Mark inline functions that don't depend on external data as constexpr.)