[libromdata] RomDataFactory: Remove #ifdefs for HAVE_LZ4 and HAVE_LZO due to MSVC issues.
MSVC doesn't like having #ifdefs within the P99_PROTECT() macro:

src\libromdata\RomDataFactory.cpp(459): error C2121: '#': invalid character: possibly the result of a macro expansion
src\libromdata\RomDataFactory.cpp(459): error C2065: 'ifdef': undeclared identifier
src\libromdata\RomDataFactory.cpp(459): error C2146: syntax error: missing ')' before identifier 'HAVE_LZ4'
src\libromdata\RomDataFactory.cpp(459): error C2143: syntax error: missing ';' before '}'

This shouldn't be a major issue, since LZ4 and LZO are almost always
enabled, and if they aren't, CisoPspReader will return an error if
ZISO or JISO is used and the library is needed.