[librpbase] Config: `return false;` instead of `break;` on invalid BoolConfig option.
The release build failed, though the debug build succeeded:

src/librpbase/config/Config.cpp: In member function ‘bool LibRpBase::Config::getBoolConfigOption(BoolConfig) const’:
src/librpbase/config/Config.cpp:715:1: error: control reaches end of non-void function [-Werror=return-type]
  715 | }
      | ^
src/librpbase/config/Config.cpp: In static member function ‘static bool LibRpBase::Config::getBoolConfigOption_default(BoolConfig)’:
src/librpbase/config/Config.cpp:772:1: error: control reaches end of non-void function [-Werror=return-type]
  772 | }
      | ^
cc1plus: some warnings being treated as errors