[kf6] Preliminary port to KDE Frameworks 6.
KF6 isn't out yet, so this is mostly just a compile test against
Qt 6.

Main changes:

- KeyStoreModel.hpp: #include "KeyStoreQt.hpp" instead of simply
  forward-defining the class.

src/kde/kf6/rom-properties-kf6_autogen/A2AGDIRYKS/moc_KeyStoreModel.cpp:151:1:   required from here
/usr/include/qt6/QtCore/qmetatype.h:858:23: error: invalid application of ‘sizeof’ to incomplete type ‘KeyStoreQt’
  858 |         static_assert(sizeof(T), "Type argument of Q_PROPERTY or Q_DECLARE_METATYPE(T*) must be fully defined");
      |                       ^~~~~~~~~

- stub-export.cpp: Don't set Qt::AA_EnableHighDpiScaling on Qt 6. It's
  always enabled on Qt 6 and this constant is now deprecated.

- AchievementsItemDelegate: QVariant::canConvert(int) is deprecated.
  The recommended replacement is QVariant::canConvert(QMetaType), which
  is Qt 6 only, or alternatively, QVariant::canConvert<T>, which is
  available in Qt 4 and Qt 5.

The only actual compile error I've hit so far is with KFileMetaData
because it uses QMap::insertMulti(), which was removed from Qt 6.