[src] span.hh: Disable as_bytes() and as_writable_bytes() on MSVC 2017 and earlier.
When compiling the 32-bit Windows version using v141_xp, it suddenly
started failing due to this code block:

src\span.hh(245): error C2059: syntax error: '<end Parse>' (compiling source file src\libromdata\Other\EXE_manifest.cpp)
src\span.hh(247): error C2988: unrecognizable template declaration/definition (compiling source file Z:\programming\rom-properties\src\libromdata\Other\EXE_manifest.cpp)
src\span.hh(247): error C2059: syntax error: '{' (compiling source file src\libromdata\Other\EXE_manifest.cpp)
src\span.hh(247): error C2143: syntax error: missing ';' before '{' (compiling source file src\libromdata\Other\EXE_manifest.cpp)
src\span.hh(247): error C2447: '{': missing function header (old-style formal list?) (compiling source file Z:\programming\rom-properties\src\libromdata\Other\EXE_manifest.cpp)
src\span.hh(252): error C2059: syntax error: '<end Parse>' (compiling source file src\libromdata\Other\EXE_manifest.cpp)
src\span.hh(254): error C2988: unrecognizable template declaration/definition (compiling source file Z:\programming\rom-properties\src\libromdata\Other\EXE_manifest.cpp)
src\span.hh(254): error C2059: syntax error: '{' (compiling source file src\libromdata\Other\EXE_manifest.cpp)
src\span.hh(254): error C2143: syntax error: missing ';' before '{' (compiling source file src\libromdata\Other\EXE_manifest.cpp)
src\span.hh(254): error C2447: '{': missing function header (old-style formal list?) (compiling source file Z:\programming\rom-properties\src\libromdata\Other\EXE_manifest.cpp)

Restricting it to MSVC 2019 and later should fix it.

TODO: Do we need to restrict it to a particular MSVC 2019 update?