[librptexture] ICO.cpp: Fix a format truncation warning.
/<<PKGBUILDDIR>>/src/librptexture/fileformat/ICO.cpp: In function ‘getIconBitmapHeaderData’:
/<<PKGBUILDDIR>>/src/librptexture/fileformat/ICO.cpp:405:58: error: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Werror=format-truncation=]
  405 |   snprintf(data.pixel_format, sizeof(data.pixel_format), "CI%u", data.bitcount);
      |                                                          ^
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:35: note: ‘__builtin___snprintf_chk’ output between 4 and 8 bytes into a destination of size 7
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |                                   ^
lto1: some warnings being treated as errors

(cherry picked from commit 997389a75fd187c1dcd8f1a380e984a2889c0daa)