[win32] clsid_common.hpp: Un-inline klass::UnregisterCLSID().
We can't use __uuidof() here in MinGW-w64 builds because the UUID
declaration is located *after* the class declaration.

The lack of inlining shouldn't be a problem in LTO builds, though.

This fixes the following errors in MinGW-w64 builds:

[ 88%] Building CXX object src/win32/CMakeFiles/rom-properties.dir/DllMain.cpp.obj
In file included from C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/x86_64-w64-mingw32/include/crtdefs.h:10:0,
                 from C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/x86_64-w64-mingw32/include/stdint.h:28,
                 from C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/lib/gcc/x86_64-w64-mingw32/7.2.0/include/stdint.h:9,
                 from C:/projects/rom-properties/src/c++11-compat.h:121,
                 from <command-line>:0:
C:\projects\rom-properties\src\win32\RP_ExtractIcon.hpp:82:1: error: specialization of 'const GUID& __mingw_uuidof() [with T = RP_ExtractIcon; GUID = _GUID]' after instantiation
 __CRT_UUID_DECL(RP_ExtractIcon, __MSABI_LONG(0xe51bc107), 0xe491, 0x4b29, 0xa6,0xa3, 0x2a, 0x43, 0x09, 0x25, 0x98, 0x02)
 ^
C:\projects\rom-properties\src\win32\RP_ExtractImage.hpp:76:1: error: specialization of 'const GUID& __mingw_uuidof() [with T = RP_ExtractImage; GUID = _GUID]' after instantiation
 __CRT_UUID_DECL(RP_ExtractImage, __MSABI_LONG(0x84573bc0), 0x9502, 0x42f8, 0x80,0x66, 0xcc, 0x52, 0x7d, 0x07, 0x79, 0xe5)
 ^
C:\projects\rom-properties\src\win32\RP_ShellPropSheetExt.hpp:95:1: error: specialization of 'const GUID& __mingw_uuidof() [with T = RP_ShellPropSheetExt; GUID = _GUID]' after instantiation
 __CRT_UUID_DECL(RP_ShellPropSheetExt, __MSABI_LONG(0x2443c158), 0xdf7c, 0x4352, 0xb4,0x35, 0xbc, 0x9f, 0x88, 0x5f, 0xfd, 0x52)
 ^
C:\projects\rom-properties\src\win32\RP_ThumbnailProvider.hpp:71:1: error: specialization of 'const GUID& __mingw_uuidof() [with T = RP_ThumbnailProvider; GUID = _GUID]' after instantiation
 __CRT_UUID_DECL(RP_ThumbnailProvider, __MSABI_LONG(0x4723df58), 0x463e, 0x4590, 0x8f,0x4a, 0x8d, 0x9d, 0xd4, 0xf4, 0x35, 0x5a)
 ^