[cmake] FindIconv.cmake: Add `return 0;` to the test code.
gcc.cmake sets `-Werror=return-type`, which breaks FindIconv.cmake's
test code. Strangely, this is only causing problems when testing with
my Debian 8 PowerPC VM...

Performing C SOURCE FILE Test Iconv_IS_BUILT_IN failed with the following output:
Change Dir: build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_3ad47"
[1/2] Building C object CMakeFiles/cmTC_3ad47.dir/src.c.o
FAILED: /usr/bin/cc    -Wall -Wextra -Wno-multichar -Werror=return-type
	-Werror=format -fstrict-aliasing -Werror=strict-aliasing -fno-common
	-fno-math-errno -Werror=implicit-function-declaration -fstack-protector-strong
	-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE
	-include build/src/config.libc.h -include src/compiler-compat.h
	-DIconv_IS_BUILT_IN -o CMakeFiles/cmTC_3ad47.dir/src.c.o   -c src.c
src.c: In function ‘main’:
src.c:11:7: error: control reaches end of non-void function [-Werror=return-type]
       }
       ^
cc1: some warnings being treated as errors
ninja: build stopped: subcommand failed.

Source file was:

.     #include <stddef.h>
.     #include <iconv.h>
      int main() {
        char *a, *b;
        size_t i, j;
        iconv_t ic;
        ic = iconv_open("to", "from");
        iconv(ic, &a, &i, &b, &j);
        iconv_close(ic);
      }