[librpbase/tests] TimegmTest: Fix MSVC 2015 build; re-enable _mkgmtime() on 64-bit MinGW-w64.
MSVCRT's _mkgmtime64() is documented as not supporting values outside of
the range [1970/01/01, 3000/12/31]. For these values, it returns -1.
Tests that have values outside of this range will now check for -1 if
using _mkgmtime64().

time_r.h: #define USING_MSVCRT_MKGMTIME if we're using _mkgmtime().

Use the "LL" suffix instead of casting to time_t. This fixes the following
errors on MSVC 2015:

src\librpbase\tests\TimegmTest.cpp(43,2): error C4146: unary minus operator applied to unsigned type, result still unsigned
src\librpbase\tests\TimegmTest.cpp(49,2): error C4146: unary minus operator applied to unsigned type, result still unsigned