[kde] RomDataView: Re-add Q_DECLARE_METATYPE(), but for RomDataPtr, not RomData.
It works with RomData on Qt6, but on Qt4 and Qt5 it breaks:

In file included from /usr/include/qt4/QtCore/qvariant.h:48:0,
                 from /usr/include/qt4/QtCore/QVariant:1,
                 from /usr/include/kurl.h:27,
                 from /usr/include/kpropertiesdialog.h:30,
                 from src/kde/plugins/RomPropertiesDialogPlugin.hpp:16,
                 from src/kde/plugins/RomPropertiesDialogPlugin.cpp:19:
/usr/include/qt4/QtCore/qmetatype.h: In instantiation of ‘void* qMetaTypeConstructHelper(const T*) [with T = LibRpBase::RomData]’:
/usr/include/qt4/QtCore/qmetatype.h:196:25:   required from ‘int qRegisterMetaType(const char*, T*) [with T = LibRpBase::RomData]’
src/kde/kde4/../RomDataView.hpp:15:1:   required from here
/usr/include/qt4/QtCore/qmetatype.h:141:22: error: invalid new-expression of abstract class type ‘LibRpBase::RomData’
         return new T();
                      ^
In file included from src/kde/kde4/../RomDataView.hpp:14:0,
                 from src/kde/plugins/RomPropertiesDialogPlugin.cpp:20:
src/kde/kde4/../../librpbase/RomData.hpp:36:16: note:   because the following virtual functions are pure within ‘LibRpBase::RomData’:
 class NOVTABLE RomData
                ^

Re-enable the romDataChanged() signal using RomDataPtr.