[libromdata] SNESPrivate::isSnesRomHeaderValid(): Work around a compile warning in gcc-5.4.0.
Compiling on Xubuntu 16.04 results in the following warning:

src/libromdata/Console/SNES.cpp: In static member function ‘static bool LibRomData::SNESPrivate::isSnesRomHeaderValid(const SNES_RomHeader*, bool)’:
src/libromdata/Console/SNES.cpp:404:55: error: comparison of promoted ~unsigned with unsigned [-Werror=sign-compare]
  if (static_cast<uint16_t>( romHeader->snes.checksum) !=
                                                       ^
cc1plus: all warnings being treated as errors

It doesn't make sense at all, but using `unsigned int` temporaries
seems to work around it. Also, use "^ 0xFFFF" instead of ~ so we
only invert the 16-bit value, not the full 32 bits of `unsigned int`.