[libromdata] Nintendo3DSSysTitles, SegaPublishers: Fix some errors when converting to namespaces.
These shouldn't be "Private" namespaces.

[ 62%] Linking CXX executable ../../bin/rpcli
../../lib/libromdata.so.1.0: undefined reference to `LibRomData::SegaPublishers::lookup(unsigned int)'
../../lib/libromdata.so.1.0: undefined reference to `LibRomData::Nintendo3DSSysTitles::lookup_sys_title(unsigned int, unsigned int, char const**)'
collect2: error: ld returned 1 exit status
src/rpcli/CMakeFiles/rpcli.dir/build.make:180: recipe for target 'bin/rpcli' failed
make[2]: *** [bin/rpcli] Error 1

This fixes a regression from commit f8ad1094f06ae7859248b528fc42df91985535fb.
([libromdata] Converted the rest of the data/ static classes to namespaces.)