[librpfile] FileSystem::get_file_size_and_mtime(): Fix incorrect filename check.
Should be checking for !filename, not filename.

This caused a warning that was handled at an error in the Linux release
build (gcc-13.2.0):

src/librpfile/FileSystem_posix.cpp: In function ‘int LibRpFile::FileSystem::get_file_size_and_mtime(const char*, off64_t*, time_t*)’:
src/librpfile/FileSystem_posix.cpp:432:24: error: argument 2 null where non-null expected [-Werror=nonnull]
  432 |         int ret = statx(AT_FDCWD, filename, 0, STATX_TYPE | STATX_MTIME | STATX_SIZE, &sbx);
      |                   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/bits/statx.h:39,
                 from /usr/include/sys/stat.h:465,
                 from src/librpfile/FileSystem_posix.cpp:15:
/usr/include/bits/statx-generic.h:61:5: note: in a call to function ‘int statx(int, const char*, int, unsigned int, statx*)’ declared ‘nonnull’
   61 | int statx (int __dirfd, const char *__restrict __path, int __flags,
      |     ^~~~~
cc1plus: some warnings being treated as errors

This fixes a regression from commit 96f50979d6f254d9ba37ae01603f57e0390a1fa7.
([librpfile] FileSystem: Add UTF-16 overloads for set_mtime(), get_mtime(), and get_file_size_and_mtime().)