Fix the MinGW-w64 build.
- tcharx.h: #include <cstring> (or <string.h>) for memcmp() when needed.

In file included from src/librpfile/xattr/XAttrReader_p.hpp:14,
                 from src/librpfile/xattr/XAttrReader_win32.cpp:10:
src/librpfile/../tcharx.h: In function ‘int _tmemcmp_inline(const TCHAR*, const TCHAR*, size_t)’:
src/librpfile/../tcharx.h:59:16: error: ‘memcmp’ was not declared in this scope
   59 |         return memcmp(s1, s2, n * sizeof(TCHAR));
      |                ^~~~~~
src/librpfile/../tcharx.h:28:1: note: ‘memcmp’ is defined in header ‘<cstring>’; this is probably fixable by adding ‘#include <cstring>’
   27 | #include <tchar.h>
  +++ |+#include <cstring>
   28 |

- #include "time_r.h" in a few more files.

- In files that already #include "time_r.h", need to include it earlier
  due to MinGW-w64 requiring _POSIX_C_SOURCE=1.