[libwin32darkmode] DarkModeCtrl.cpp: Remove the CHARFORMAT2 initializer list.
MSVC 2015 doesn't like it:

src\libwin32darkmode\DarkModeCtrl.cpp(170): error C2440: 'initializing':
cannot convert from 'initializer list' to 'CHARFORMAT2W'
  src\libwin32darkmode\DarkModeCtrl.cpp(170): note: No constructor could
  take the source type, or constructor overload resolution was ambiguous