[librpbase] RpImageLoader::load(const IRpFilePtr&): Needs to be static inline.
Otherwise, we end up with multiple definitions in the Linux build:

mold: error: duplicate symbol: src/kde/kf5/CMakeFiles/RomThumbnailCreator-kf5.dir/__/plugins/RomThumbCreator_p.cpp.o: src/kde/kf5/CMakeFiles/RomThumbnailCreator-kf5.dir/__/plugins/RomThumbnailCreator.cpp.o: LibRpBase::RpImageLoader::load(std::shared_ptr<LibRpFile::IRpFile> const&)