[googletest] Disable gtest_main and gmock_main.
The recent PIC changes for the internal TinyXML2 somehow broke compiling
gtest_main on Windows:

extlib\googletest\googletest\src\gtest_main.cc(48): error C2491: 'main':
    definition of dllimport function not allowed

Also disable gmock_main, since it depends on gtest_main.

We aren't actually using these, so it's not an issue.
(We implement our own main() in gtest_init.cpp.)

[extlib] CMakeLists.txt: Rename SET_EXTLIB_PROPERTIES_PIC() to
SET_EXTLIB_PROPERTIES_PIC_ONLY(), since SET_EXTLIB_PROPERTIES()
also sets POSITION_INDEPENDENT_CODE=TRUE.

Also use SET_EXTLIB_PROPERTIES_PIC_ONLY() for shared libraries that
may be installed, since we can't use SET_EXTLIB_PROPERTIES().