[libromdata] EXEPrivate::addFields_NE_Entry(): Fix the bsearch() key on Debian 8 ppc.
gcc-4.9.2-10+deb8u1 on Debian 8 (ppc) can't convert "" to vhvc::span<>,
so we have to explicitly convert it ourselves.

../src/libromdata/Other/EXE_NE.cpp: In lambda function:
../src/libromdata/Other/EXE_NE.cpp:718:64: error: could not convert ‘(const char*)""’ from ‘const char*’ to ‘vhvc::span<const char>’
    const Entry key = {"", ordinal, 0, 0, 0, false, false, false};
                                                                ^