[libromdata] PEResourceReader: #include "uvector.h" after <unordered_map>.
Something in uvector.h is causing clang to get really confused if
uvector.h is included before unordered_map:

[  0%] Building CXX object src/libromdata/CMakeFiles/romdata8.dir/disc/PEResourceReader.cpp.o
In file included from /home/david/programming/rom-properties/src/libromdata/disc/PEResourceReader.cpp:40:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include/g++-v6/unordered_map:47:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include/g++-v6/bits/hashtable.h:35:
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include/g++-v6/bits/hashtable_policy.h:1083:45: error: C++ requires a type specifier for all declarations
        noexcept( noexcept(declval<const _Hash&>()(declval<const _Key&>(),
                                                   ^
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include/g++-v6/bits/hashtable_policy.h:1083:45: error: 'declval' cannot be the name of a parameter
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include/g++-v6/bits/hashtable_policy.h:1084:11: error: C++ requires a type specifier for all declarations
                                                   (std::size_t)0)) )
                                                    ^
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include/g++-v6/bits/hashtable_policy.h:1084:23: error: expected ')'
                                                   (std::size_t)0)) )
                                                                ^
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include/g++-v6/bits/hashtable_policy.h:1083:44: note: to match this '('
        noexcept( noexcept(declval<const _Hash&>()(declval<const _Key&>(),
                                                  ^