[kf5] CMakeLists.txt: Missed two ${RTC_SUFFIX} additions.
This broke the KF5 build on Codecov:

In file included from rom-properties/src/kde/kf5/RomThumbnailCreator-kf5-dir_autogen/BKZOEHIFDQ/moc_RomThumbnailCreator.cpp:10,
                 from rom-properties/src/kde/kf5/RomThumbnailCreator-kf5-dir_autogen/mocs_compilation.cpp:2:
rom-properties/src/kde/kf5/RomThumbnailCreator-kf5-dir_autogen/BKZOEHIFDQ/../../../plugins/RomThumbnailCreator.hpp:13:10: fatal error: QtCore/qglobal.h: No such file or directory
   13 | #include <QtCore/qglobal.h>
      |          ^~~~~~~~~~~~~~~~~~