[kde] Work around an issue where plugins try including fmt/format.h without linking to fmt.
Add a macro RP_NO_INCLUDE_LIBFMT_IN_STDAFX_H. This macro is defined by
the various KDE plugin projects that don't need libfmt.

All stdafx.h files that include fmt headers will now disable those
inclusions if RP_NO_INCLUDE_LIBFMT_IN_STDAFX_H is defined.

Removing stdafx.h from the KDE plugins wasn't a viable option because
e.g. ProxyForUrl.cpp includes it, and is part of the main KDE plugin
as well as the sub-plugins.

This should fix the following error when building on a system that
doesn't have a system-wide libfmt and is building the KDE UI frontend(s):

In file included from src/kde/kf5/../stdafx.h:35,
                 from src/kde/plugins/RomThumbCreator_p.cpp:9:
src/kde/kf5/../../rp-libfmt.h:14:10: fatal error: fmt/format.h: No such file or directory
   14 | #include <fmt/format.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.