[librpbyteswap] bitstuff.h: Don't `#define inline` if compiling C++ code.
When compiling with MSVC with PCH disabled, due to different include
orders, this ends up breaking the STL:

C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.51.36231\include\xkeycheck.h(267,1): error C1189: #error:  The C++ Standard Library forbids macroizing the keyword "inline". Enable warning C4005 to find the forbidden define.
  (compiling source file '../../../../src/librptexture/ImageSizeCalc.cpp')