[librpfile] IRpFile: Remove `padding`.
clang complains because it's unused:

src/librpfile/IRpFile.hpp:309:10: error: private field 'm_padding' is not used [-Werror,-Wunused-private-field]
  309 |         uint8_t m_padding;      // pad to 8 bytes
      |                 ^
1 error generated.

This effectively reverts commit 9d19c283791850b8a2d260168dd2d6dc5f04324b
([librpfile] IRpFile: Explicitly add a byte of padding.)
but it isn't a direct revert due to un-indenting.