[rp-download] rp-download.cpp: gcc's printf attribute doesn't support wchar_t.
src/rp-download/rp-download.cpp:93:36: error: 'format' attribute argument 2 value '1' refers to parameter type 'const TCHAR*' {aka 'const wchar_t*'}
   93 | show_error(const TCHAR *format, ...)
      |                                    ^