[rpcli] CMakeLists.txt: Link in libdl if it's required for dlopen().
glibc-2.34 merged libdl into libc. Older versions, e.g. glibc-2.23
(Ubuntu 16.04), still have a separate libdl. Without this change,
rpcli fails to link:

/usr/bin/ld: CMakeFiles/rpcli.dir/rp_sixel.cpp.o: undefined reference to symbol 'dlopen@@GLIBC_2.1'
//lib/i386-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status