[libromdata] CisoPspDlopen: Use a custom pthread_once_inl_t type.
On macOS (and FreeBSD), pthread_once_t is actually a struct, not a simple
int or long. ATOMIC_EXCHANGE() fails in that case:

src/libromdata/disc/CisoPspDlopen.cpp:127:2: error: invalid operands to binary expression ('pthread_once_t' (aka '_opaque_pthread_once_t') and 'int')
  127 |         pthread_once_inl(&m_once_lz4, init_pfn_LZ4_int);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/libromdata/disc/CisoPspDlopen.cpp:61:22: note: expanded from macro 'pthread_once_inl'
   61 |         if (*(once_control) != 1) { \
      |             ~~~~~~~~~~~~~~~ ^  ~
src/libromdata/disc/CisoPspDlopen.cpp:127:2: error: address argument to atomic builtin must be a pointer to integer or pointer ('pthread_once_t *' (aka '_opaque_pthread_once_t *') invalid)
  127 |         pthread_once_inl(&m_once_lz4, init_pfn_LZ4_int);
      |         ^                ~~~~~~~~~~~
src/libromdata/disc/CisoPspDlopen.cpp:67:12: note: expanded from macro 'pthread_once_inl'
   67 |                         switch (ATOMIC_CMPXCHG(once_control, 0, 2)) { \
      |                                 ^              ~~~~~~~~~~~~
src/libromdata/../librpthreads/Atomics.h:41:44: note: expanded from macro 'ATOMIC_CMPXCHG'
   41 | #    define ATOMIC_CMPXCHG(ptr, cmp, xchg)      __sync_val_compare_and_swap(ptr, cmp, xchg)
      |                                                 ^                           ~~~
src/libromdata/disc/CisoPspDlopen.cpp:127:2: error: address argument to atomic builtin must be a pointer to integer or pointer ('pthread_once_t *' (aka '_opaque_pthread_once_t *') invalid)
  127 |         pthread_once_inl(&m_once_lz4, init_pfn_LZ4_int);
      |         ^                ~~~~~~~~~~~
src/libromdata/disc/CisoPspDlopen.cpp:72:6: note: expanded from macro 'pthread_once_inl'
   72 |                                         ATOMIC_EXCHANGE(once_control, 1); \
      |                                         ^               ~~~~~~~~~~~~
src/libromdata/../librpthreads/Atomics.h:42:40: note: expanded from macro 'ATOMIC_EXCHANGE'
   42 | #    define ATOMIC_EXCHANGE(ptr, val)           __sync_lock_test_and_set(ptr, val)
      |                                                 ^                        ~~~

Use a custom pthread_once_inl_t type that's typedef'd to int.

Also, instead of returning from pthread_once_inl() (which actually returns
from the function that called the macro), use a `run` variable and break;.