Revert "[librpsecure] os-secure_linux.c: Mark clone_params[] as static."
This reverts commit 0e7c5d78f0d9f64f36c12481676943c8ed0d22b1.

This breaks on travis-ci with Ubuntu 14.04:

[  6%] Building C object src/librpsecure/CMakeFiles/rpsecure.dir/os-secure_linux.c.o
In file included from /home/travis/build/GerbilSoft/rom-properties/src/librpsecure/os-secure.h:21:0,
                 from /home/travis/build/GerbilSoft/rom-properties/src/librpsecure/os-secure_linux.c:10:
/home/travis/build/GerbilSoft/rom-properties/src/librpsecure/os-secure_linux.c: In function ‘rp_secure_enable’:
/home/travis/build/GerbilSoft/rom-properties/src/librpsecure/os-secure_linux.c:108:4: error: initializer element is not constant
    SCMP_A0(SCMP_CMP_MASKED_EQ, CLONE_THREAD, CLONE_THREAD),
    ^
/home/travis/build/GerbilSoft/rom-properties/src/librpsecure/os-secure_linux.c:108:4: error: (near initialization for ‘clone_params[0]’)