[zstd] seekable_format: Fix linker issues.
- zstd_seekable.h: Disable ZSTDLIB_API, since this is being linked as a
  static library and not as a DLL.

- Add xxhash.c. This is technically compiled as part of the ZSTD library,
  but it isn't exported.

Fixes these linker errors for the upcoming Z3DSReader:

extlib\zstd\contrib\seekable_format\zstdseek_decompress.c(230,16): warning C4273: 'ZSTD_seekable_create': inconsistent dll linkage
      extlib\zstd\contrib\seekable_format\zstd_seekable.h(165,28):
      see previous definition of 'ZSTD_seekable_create'

Z3DSReader.obj : error LNK2019: unresolved external symbol __imp_ZSTD_seekable_create referenced in function "public: __cdecl LibRomData::Z3DSReaderPrivate::Z3DSReaderPrivate(class LibRomData::Z3DSReader *)" (??0Z3DSReaderPrivate@LibRomData@@QEAA@PEAVZ3DSReader@1@@Z)
Z3DSReader.obj : error LNK2019: unresolved external symbol __imp_ZSTD_seekable_free referenced in function "public: __cdecl LibRomData::Z3DSReaderPrivate::Z3DSReaderPrivate(class LibRomData::Z3DSReader *)" (??0Z3DSReaderPrivate@LibRomData@@QEAA@PEAVZ3DSReader@1@@Z)
Z3DSReader.obj : error LNK2019: unresolved external symbol __imp_ZSTD_seekable_decompress referenced in function "public: virtual unsigned __int64 __cdecl LibRomData::Z3DSReader::read(void *,unsigned __int64)" (?read@Z3DSReader@LibRomData@@UEAA_KPEAX_K@Z)
Z3DSReader.obj : error LNK2019: unresolved external symbol __imp_ZSTD_seekable_initAdvanced referenced in function "public: __cdecl LibRomData::Z3DSReaderPrivate::Z3DSReaderPrivate(class LibRomData::Z3DSReader *)" (??0Z3DSReaderPrivate@LibRomData@@QEAA@PEAVZ3DSReader@1@@Z)
bin\Debug\romdata-8d.dll : fatal error LNK1120: 4 unresolved externals

zstd_seekable_format.lib(zstdseek_decompress.obj) : error LNK2019: unresolved external symbol ZSTD_XXH64_reset referenced in function ZSTD_seekable_decompress
zstd_seekable_format.lib(zstdseek_decompress.obj) : error LNK2019: unresolved external symbol ZSTD_XXH64_update referenced in function ZSTD_seekable_decompress
zstd_seekable_format.lib(zstdseek_decompress.obj) : error LNK2019: unresolved external symbol ZSTD_XXH64_digest referenced in function ZSTD_seekable_decompress
bin\Debug\romdata-8d.dll : fatal error LNK1120: 3 unresolved externals