RefBase.hpp: #include <type_traits>
This fixes the KF5 build on Ubuntu 16.04. Not sure why it didn't cause
problems anywhere else...

In file included from src/kde/kf5/../../librpbase/img/IconAnimData.hpp:13:0,
                 from src/kde/kf5/../../../../../../..src/kde/DragImageLabel.hpp:19,
                 from src/kde/kf5/moc_DragImageLabel.cpp:9,
                 from src/kde/kf5/rom-properties-kf5_automoc.cpp:2:
src/kde/kf5/../../RefBase.hpp: In constructor ‘unique_RefBase<T>::unique_RefBase(T*)’:
src/kde/kf5/../../RefBase.hpp:95:18: error: ‘is_base_of’ is not a member of ‘std’
    static_assert(std::is_base_of<RefBase, T>::value,
                  ^
src/kde/kf5/../../RefBase.hpp:95:41: error: expected primary-expression before ‘,’ token
    static_assert(std::is_base_of<RefBase, T>::value,
                                         ^
src/kde/kf5/../../RefBase.hpp:95:43: error: expected string-literal before ‘T’
    static_assert(std::is_base_of<RefBase, T>::value,
                                           ^
src/kde/kf5/../../RefBase.hpp:95:43: error: expected ‘)’ before ‘T’