[cmake] CPUInstructionSetFlags.cmake: Set NEON_FLAGS to "-marm -mfpu=neon" on 32-bit ARM.
[librpbyteswap,librptexture] Apply NEON_FLAGS on 32-bit ARM.

The Ubuntu 18.04 armhf build failed to compile:

/<<PKGBUILDDIR>>/src/librpbyteswap/byteswap_neon.c: In function ‘rp_byte_swap_16_array_neon’:
/usr/lib/gcc/arm-linux-gnueabihf/7/include/arm_neon.h:11880:1: error: inlining failed in call to always_inline ‘vst2q_u16’: target specific option mismatch
 vst2q_u16 (uint16_t * __a, uint16x8x2_t __b)
 ^~~~~~~~~
/<<PKGBUILDDIR>>/src/librpbyteswap/byteswap_neon.c:48:3: note: called from here
   vst2q_u16(ptr, vec);
   ^~~~~~~~~~~~~~~~~~~

It seems NEON is disabled by default on armhf.

NOTE: Not rebuilding for armhf on Ubuntu 18.04.
(cherry picked from commit 66c43ccb4a659bdb5167f863afb12288f395ed00)