[libromdata] AndroidManifestXML: Return a pointer from decompressAndroidBinaryXml().
PugiXML 1.7-2 (Xubuntu 16.04) has a private copy constructor:

In file included from src/libromdata/Handheld/AndroidManifestXML.hpp:15:0,
                 from src/libromdata/Handheld/AndroidManifestXML.cpp:12:
/usr/include/pugixml.hpp: In static member function ‘static pugi::xml_document LibRomData::AndroidManifestXMLPrivate::decompressAndroidBinaryXml(const uint8_t*, size_t)’:
/usr/include/pugixml.hpp:947:3: error: ‘pugi::xml_document::xml_document(const pugi::xml_document&)’ is private
   xml_document(const xml_document&);
   ^
src/libromdata/Handheld/AndroidManifestXML.cpp:434:9: error: within this context
  return doc;
         ^

Return a pointer instead of dealing with weird copy shenanigans.
This makes the code a bit cleaner too, since we have to use a
pointer anyway to work around delay-load issues.