[librptext] conversion_win32.cpp: #include <cstdint>
This broke the MinGW-w64 build (for both i386 and amd64), but not the
MSVC build for some reason:

src/librptext/conversion_win32.cpp: In function ‘std::u16string LibRpText::cpN_to_utf16(unsigned int, const char*, int, unsigned int)’:
src/librptext/conversion_win32.cpp:164:39: error: ‘uint8_t’ does not name a type
  164 |                                 const uint8_t chr = static_cast<uint8_t>(*p);
      |                                       ^~~~~~~
src/librptext/conversion_win32.cpp:22:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
   21 | #include "libwin32common/RpWin32_sdk.h"
  +++ |+#include <cstdint>
   22 |
src/librptext/conversion_win32.cpp:165:37: error: ‘chr’ was not declared in this scope; did you mean ‘char’?
  165 |                                 if (chr == 0) {
      |                                     ^~~
      |                                     char