[libromdata/tests] GcnFstTest: Use `0UL` instead of `0` when comparing to file_info.size_filename.
extlib\googletest\googletest\include\gtest/gtest.h(1444): error C2220: warning treated as error - no 'object' file generated (compiling source file src\libromdata\tests\disc\GcnFstTest.cpp)
  src\libromdata\tests\disc\GcnFstTest.cpp(546): note: see reference to function template instantiation 'testing::AssertionResult testing::internal::CmpHelperGT<unsigned long,int>(const char *,const char *,const T1 &,const T2 &)' being compiled
          with
          [
              T1=unsigned long,
              T2=int
          ]
extlib\googletest\googletest\include\gtest/gtest.h(1444): warning C4018: '>': signed/unsigned mismatch (compiling source file src\libromdata\tests\disc\GcnFstTest.cpp)