force_inline.h: s/FORCEINLINE/RP_FORCEINLINE/
MinGW-w64 defines FORCEINLINE itself, and our custom definition breaks
MinGW-w64's headers in weird ways: (MinGW-w64 14.0.0, gcc-16.1.0)

/usr/x86_64-pc-linux-gnu/x86_64-w64-mingw32/binutils-bin/2.46.0/ld: lib/librpcpuid.a(cpuflags_x86.c.obj): in function `NtCurrentTeb':
/usr/x86_64-w64-mingw32/usr/include/winnt.h:10416: multiple definition of `NtCurrentTeb'; src/libromdata/CMakeFiles/romdata.dir/__/libwin32common/DelayLoadHelper.c.obj:/usr/x86_64-w64-mingw32/usr/include/winnt.h:10416: first defined here
/usr/x86_64-pc-linux-gnu/x86_64-w64-mingw32/binutils-bin/2.46.0/ld: lib/librpcpuid.a(cpuflags_x86.c.obj): in function `GetCurrentFiber':
/usr/x86_64-w64-mingw32/usr/include/winnt.h:10420: multiple definition of `GetCurrentFiber'; src/libromdata/CMakeFiles/romdata.dir/__/libwin32common/DelayLoadHelper.c.obj:/usr/x86_64-w64-mingw32/usr/include/winnt.h:10420: first defined here
/usr/x86_64-pc-linux-gnu/x86_64-w64-mingw32/binutils-bin/2.46.0/ld: lib/librpcpuid.a(cpuflags_x86.c.obj): in function `GetFiberData':
/usr/x86_64-w64-mingw32/usr/include/winnt.h:10446: multiple definition of `GetFiberData'; src/libromdata/CMakeFiles/romdata.dir/__/libwin32common/DelayLoadHelper.c.obj:/usr/x86_64-w64-mingw32/usr/include/winnt.h:10446: first defined here

The MinGW-w64 build compiles again.

FIXME: This function should be inlined, but isn't:

In file included from /home/david/programming/rom-properties/src/libi18n/libintl-wrapper/libintl.h:2,
                 from /home/david/programming/rom-properties/src/librptext/../libi18n/gettext.h:36,
                 from /home/david/programming/rom-properties/src/librptext/../libi18n/i18n.hpp:30,
                 from /home/david/programming/rom-properties/src/librptext/formatting.cpp:13:
/home/david/p/rp.mingw64/extlib/gettext/gettext-runtime/intl/libgnuintl.h:1091:7: warning: ‘char* setlocale(int, const char*)’ redeclared without dllimport attribute after being referenced with dll linkage
 1091 | char *setlocale (int __category, const char *__locale)
      |       ^~~~~~~~~