[libi18n] NOP_C_() and C_() now return `const char8_t*`.
It's handled by casting the `const char*` from gettext to
`const char8_t`, which works because gettext already uses UTF-8.

The GTK and KDE builds are fully updated, but the Windows build is
currently failing:

include\xlocnum(255,1): error C2491: 'std::numpunct<_Elem>::id':
definition of dllimport static data member not allowed

Related changes:
- TextFuncs: formatFileSize() now returns u8string.
- TextOut_json.cpp: New macros U8S2C() and U8C2C().
- Changed a lot of functions that returned localized strings to
  return `const char8_t*` instead of `const char*`.
- RpJpeg: Removed localization of "libjpeg error: %s".
  The error message wouldn't be localized anyway, and most users
  won't see it.
- Re-enabled some commented-out i18n in PowerVR3 and ValveVTF.
- Wii_WAD_Header: Changed `type` to a union of uint32_t and char[4].
- Undo some ternary operators where the parameters are `const char8_t*`
  and `u8string`, since this would unnecessarily convert the char8_t to
  a u8string.
- NCCHReader::contentType(): Return `const char8_t*`.
- TImageTypesConfig::saveWriteEntry(): Still `const char*` since the
  values are both ASCII, not UTF-8.

FIXME: TextOut_text.cpp has ostream operator<<() for char8_t and u8string.
I tried putting it in c++11-compat.h, but neither MSVC nor GCC detected
them if they weren't in the namespace they're used in...