[svrplus] svrplus.c, check_system_architectures(): Missing `default:` case.
src/svrplus/svrplus.c: In function ‘check_system_architectures’:
src/svrplus/svrplus.c:1124:17: error: enumeration value ‘CPU_MAX’ not handled in switch [-Werror=switch]
 1124 |                 switch (ifm_to_SysArch(nativeMachine)) {
      |                 ^~~~~~