[debian] Disable system libzstd for now.
Launchpad build servers are failing on Ubuntu 20.04 "Focal" Fossa:

/tmp/ccV8szdy.ltrans3.ltrans.o: In function `mz_stream_zstd_compress':
./build/src/libromdata/tests/./extlib/minizip-ng/mz_strm_zstd.c:199: undefined reference to `ZSTD_compressStream2'
collect2: error: ld returned 1 exit status

ZSTD_compressStream2 *is* present in zstd-1.4.4, so I'm not sure why
this is happening. I'll diagnose it later.

zstd isn't actually used at runtime right now, so it's not too important.