[librptexture] ImageDecoder_Linear_neon16.cpp: MaskGR88 is 32-bit, not 16-bit.
This didn't cause any test failures, but it caused compile errors on
Ubuntu 16.04 on Launchpad:

/<<PKGBUILDDIR>>/src/librptexture/decoder/ImageDecoder_Linear_neon16.cpp: In function ‘LibRpTexture::rp_image_ptr LibRpTexture::ImageDecoder::fromLinear16_neon(LibRpTexture::ImageDecoder::PixelFormat, int, int, const uint16_t*, size_t, int)’:
/<<PKGBUILDDIR>>/src/librptexture/decoder/ImageDecoder_Linear_neon16.cpp:473:56: note: use -flax-vector-conversions to permit conversions between vectors with differing element types or numbers of subparts
    const uint16x8_t MaskGR88_vec = vdupq_n_u32(MaskGR88);
                                                        ^
/<<PKGBUILDDIR>>/src/librptexture/decoder/ImageDecoder_Linear_neon16.cpp:473:56: error: cannot convert ‘uint32x4_t {aka __vector(4) unsigned int}’ to ‘const uint16x8_t {aka const __vector(8) short unsigned int}’ in initialization
/<<PKGBUILDDIR>>/src/librptexture/decoder/ImageDecoder_Linear_neon16.cpp:487:51: error: cannot convert ‘uint32x4_t {aka __vector(4) unsigned int}’ to ‘uint16x8_t {aka __vector(8) short unsigned int}’ for argument ‘1’ to ‘uint16x8_t vandq_u16(uint16x8_t, uint16x8_t)’
      px.val[0] = vandq_u16(px.val[0], MaskGR88_vec);
                                                   ^
/<<PKGBUILDDIR>>/src/librptexture/decoder/ImageDecoder_Linear_neon16.cpp:488:51: error: cannot convert ‘uint32x4_t {aka __vector(4) unsigned int}’ to ‘uint16x8_t {aka __vector(8) short unsigned int}’ for argument ‘1’ to ‘uint16x8_t vandq_u16(uint16x8_t, uint16x8_t)’
      px.val[1] = vandq_u16(px.val[1], MaskGR88_vec);
                                                   ^
/<<PKGBUILDDIR>>/src/librptexture/decoder/ImageDecoder_Linear_neon16.cpp:491:51: error: cannot convert ‘uint32x4_t {aka __vector(4) unsigned int}’ to ‘uint16x8_t {aka __vector(8) short unsigned int}’ for argument ‘1’ to ‘uint16x8_t vorrq_u16(uint16x8_t, uint16x8_t)’
      px.val[0] = vorrq_u16(px.val[0], Mask32_A_vec);
                                                   ^
/<<PKGBUILDDIR>>/src/librptexture/decoder/ImageDecoder_Linear_neon16.cpp:492:51: error: cannot convert ‘uint32x4_t {aka __vector(4) unsigned int}’ to ‘uint16x8_t {aka __vector(8) short unsigned int}’ for argument ‘1’ to ‘uint16x8_t vorrq_u16(uint16x8_t, uint16x8_t)’
      px.val[1] = vorrq_u16(px.val[1], Mask32_A_vec);
                                                   ^

Note that gcc is usually more strict with regards to ARM vector types
compared to clang.

(cherry picked from commit abde547bcd2fb43ae224d09e9a10f42521818f4f)