[librpfile] MemFile: Export the entire class, not just the constructor.
Launchpad's Ubuntu 18.04 build (gcc-7) failed:

/tmp/cclqxa26.ltrans0.ltrans.o: In function `LibRpFile::MemFile::~MemFile()':
./build/src/librpbase/tests/./src/librpbase/tests/../../librpfile/MemFile.hpp:45: undefined reference to `vtable for LibRpFile::MemFile'
/tmp/cclqxa26.ltrans0.ltrans.o: In function `RefBase::unref()':
./build/src/librpbase/tests/./src/librpbase/tests/../../librpfile/MemFile.hpp:45: undefined reference to `vtable for LibRpFile::MemFile'
/tmp/cclqxa26.ltrans0.ltrans.o: In function `LibRpBase::Tests::RpPngFormatTest::TearDown()':
./build/src/librpbase/tests/./src/librpbase/tests/../../librpfile/MemFile.hpp:45: undefined reference to `vtable for LibRpFile::MemFile'
/tmp/cclqxa26.ltrans0.ltrans.o: In function `LibRpFile::MemFile::~MemFile()':
./build/src/librpbase/tests/./src/librpbase/tests/../../librpfile/MemFile.hpp:45: undefined reference to `vtable for LibRpFile::MemFile'
collect2: error: ld returned 1 exit status
src/librpbase/tests/CMakeFiles/RpPngFormatTest.dir/build.make:107: recipe for target 'bin/RpPngFormatTest' failed
make[3]: *** [bin/RpPngFormatTest] Error 1

Also export IRpFile and RefBase because MSVC complained:

src\librpfile/MemFile.hpp(23,1): warning C4275: non dll-interface class 'LibRpFile::IRpFile' used as base for dll-interface class 'LibRpFile::MemFile'
src\librpfile\IRpFile.hpp(33,1): warning C4275: non dll-interface class 'RefBase' used as base for dll-interface class 'LibRpFile::IRpFile'
src\librpfile/MemFile.hpp(150,15): warning C4251: 'LibRpFile::MemFile::m_filename': class 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' needs to have dll-interface to be used by clients of class 'LibRpFile::MemFile'

I'm not sure about the std::string issue, though...

This shouldn't affect the ABI significantly, so I'm not going to bump
the SOVERSION.

(cherry picked from commit 7be82496247c32d726c8089bdedbfa03a22c33f7)