[libromdata] AmiiboData: Only check the character ID in std::lower_bound().
Checking both character ID and variant ID seemingly results in an
incorrect result. This was identified by enabling _GLIBCXX_DEBUG:

[ RUN      ] Amiibo/RomHeaderTest.Text/_3AZ__03___Toon_Link__The_Wind_Waker__nfp
/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/stl_algo.h:1970:
In function:
    _FIter std::lower_bound(_FIter, _FIter, const _Tp&, _Compare) [with
    _FIter = const _CharVariantTableEntry*; _Tp = _CharVariantTableEntry;
    _Compare = LibRomData::AmiiboData::lookup_char_name(uint32_t)
    const::<lambda(const CharVariantTableEntry&, const
    CharVariantTableEntry&)>]

Error: elements in iterator range [first, last) are not partitioned by the
predicate __comp and value __val.

Objects involved in the operation:
    iterator "first" @ 0x7fffffffbbb8 {
      type = _CharVariantTableEntry const* (constant iterator);
    }
    iterator "last" @ 0x7fffffffbbb0 {
      type = _CharVariantTableEntry const* (constant iterator);
    }

Additionally, the Character Variants were all wrong. For the above
Toon Link test, it ended up getting the 0x00 variant for Link instead
of the correct Toon Link variant.

This was likely broken since switching to std::lower_bound() in v2.1,
though it's possible that the bsearch() version was also broken.

Reworked it to only use the Character ID in std::lower_bound(). After
finding the first match, use a linear search to find the correct
Character Variant.

Note that this only affects the Character Variant field. All other
fields only used a single search key.

[libromdata/tests] Re-generated test results for Amiibo.