[kde/tests] Create separate kde4, kf5, and kf6 subdirectories.
The subdirectories are needed in order to prevent collisions with e.g.
different versions of automoc.

When building for KDE4 and KF5 on Ubuntu 16.04, with tests enabled,
this happened:

[ 81%] Building CXX object src/kde/tests/CMakeFiles/ListDataSortProxyModelTest_kf5.dir/ListDataSortProxyModelTest_kf5_automoc.cpp.o
In file included from src/kde/tests/ListDataSortProxyModelTest_kf5_automoc.cpp:2:0:
src/kde/tests/moc_ListDataModel.cpp:13:2: error: #error "This file was generated using the moc from 4.8.7. It"
.#error "This file was generated using the moc from 4.8.7. It"
  ^
src/kde/tests/moc_ListDataModel.cpp:14:2: error: #error "cannot be used with the include files from this version of Qt."
.#error "cannot be used with the include files from this version of Qt."
  ^
src/kde/tests/moc_ListDataModel.cpp:15:2: error: #error "(The moc has changed too much.)"
.#error "(The moc has changed too much.)"
  ^

Using subdirectories fixes this.

kde/tests/kde4: Set CMAKE_AUTOMOC=ON, since it defaults to OFF for
some reason. (TODO: Do this in the base kde directory?)