[libromdata] EXEPrivate::addFields_PE_Manifest(): Use `enum class` instead of `typedef enum`.
clang complained about unused typedefs, since we only used the enum values
and not the typedef name.

enum class does require some extra casting, but it works better here.

Fixes these clang warnings:

src/libromdata/Other/EXE_manifest.cpp:273:4: error: unused typedef 'WindowsSettings_t' [-Werror,-Wunused-local-typedef]
  273 |         } WindowsSettings_t;
      |           ^
src/libromdata/Other/EXE_manifest.cpp:346:4: error: unused typedef 'OS_Compatibility_t' [-Werror,-Wunused-local-typedef]
  346 |         } OS_Compatibility_t;
      |           ^
2 errors generated.