[cmake] gcc.cmake: Reduce -Wheader-hygiene to a warning.
clang complains about moc headers due to how automoc handles things:

In file included from build/src/kde/kf5/overlayiconplugin_rom-properties-kf5_autogen/mocs_compilation.cpp:2:
build/src/kde/kf5/overlayiconplugin_rom-properties-kf5_autogen/BKZOEHIFDQ/moc_OverlayIconPluginKF5.cpp:1340:17: error: using namespace directive in global context in header [-Werror,-Wheader-hygiene]
 1340 | using namespace RomPropertiesKF5;
      |                 ^
1 error generated.