[librpbase] SemaphoreMac.cpp: `semaphore_t` is a typedef for `unsigned int`.
Initialize it to 0 instead of nullptr.

Remove m_isInit, since we can just check if m_sem != 0.

Also, #include <mach/mach_traps.h> for mach_task_self().

This fixes the following build errors on Mac OS X:

In file included from src/libcachemgr/CacheManager.cpp:24:
In file included from src/libcachemgr/CacheManager.hpp:26:
In file included from src/libcachemgr/../librpbase/threads/Semaphore.hpp:34:
src/libcachemgr/../librpbase/threads/SemaphoreMac.cpp:77:4: error: cannot initialize a member subobject of type 'semaphore_t' (aka 'unsigned int') with an rvalue of type 'nullptr_t'
        : m_sem(nullptr)
          ^     ~~~~~~~
src/libcachemgr/../librpbase/threads/SemaphoreMac.cpp:79:39: error: use of undeclared identifier 'mach_task_self'
        kern_return_t ret = semaphore_create(mach_task_self(), &m_sem, SYNC_POLICY_FIFO, count);
                                             ^
src/libcachemgr/../librpbase/threads/SemaphoreMac.cpp:95:21: error: use of undeclared identifier 'mach_task_self'
                semaphore_destroy(mach_task_self(), m_sem);
                                  ^