[libromdata] ParamSFOPrivate::readString(): Need to use const_cast<char*>(str.data()).
string::data() returns a non-const pointer as of C++17. Earlier versions
return a const pointer. In general, it *should* be usable for writing
in earlier versions, though I suppose it's possible that older versions
of gcc that used copy-on-write strings might have issues...

This fixes a compile error on gcc-5.4 on Ubuntu 16.04:

src/libromdata/Common/ParamSFO.cpp: In member function ‘int LibRomData::ParamSFOPrivate::readString(uint32_t, size_t, std::__cxx11::string&)’:
src/libromdata/Common/ParamSFO.cpp:176:40: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
  if (file->seekAndRead(offset, str.data(), length) != length) {
                                        ^
In file included from src/libromdata/../librpbase/RomData.hpp:27:0,
                 from src/libromdata/Common/ParamSFO.hpp:12,
                 from src/libromdata/Common/ParamSFO.cpp:10:
src/libromdata/../librpfile/IRpFile.hpp:240:16: note:   initializing argument 2 of ‘size_t LibRpFile::IRpFile::seekAndRead(off64_t, void*, size_t)’
  inline size_t seekAndRead(off64_t pos, void *ptr, size_t size)
                ^