[libromdata] RomDataFactory: Move the XboxDisc check to the array.
Check for extracted XDVDFS afterwards if the array check fails.

XboxDisc.hpp: Instead of an optional parameter, add an inline wrapper
function that sets pWave = nullptr. This fixes a build error with the
function pointer array.

src/libromdata/RomDataFactory.cpp: In static member function ‘static LibRpBase::RomData* LibRomData::RomDataFactoryPrivate::checkISO(LibRpFile::IRpFile*)’:
src/libromdata/RomDataFactory.cpp:506:2: error: no matches converting function ‘isRomSupported_static’ to type ‘pfnIsRomSupported_ISO_t’ {aka ‘int (*)(const struct _ISO_Primary_Volume_Descriptor*)’}
  506 |  };
      |  ^
In file included from src/libromdata/RomDataFactory.cpp:61:
src/libromdata/Console/XboxDisc.hpp:32:14: note: candidates are: ‘static int LibRomData::XboxDisc::isRomSupported_static(const ISO_Primary_Volume_Descriptor*, uint8_t*)’
   32 |   static int isRomSupported_static(
      |              ^~~~~~~~~~~~~~~~~~~~~
In file included from src/libromdata/../librpbase/RomData.hpp:14,
                 from src/libromdata/stdafx.h:67,
                 from src/libromdata/RomDataFactory.cpp:9:
src/libromdata/../librpbase/RomData_decl.hpp:44:14: note:                 ‘static int LibRomData::XboxDisc::isRomSupported_static(const LibRpBase::RomData::DetectInfo*)’
   44 |   static int isRomSupported_static(const DetectInfo *info); \
      |              ^~~~~~~~~~~~~~~~~~~~~
src/libromdata/Console/XboxDisc.hpp:17:1: note: in expansion of macro ‘ROMDATA_DECL_BEGIN’
   17 | ROMDATA_DECL_BEGIN(XboxDisc)
      | ^~~~~~~~~~~~~~~~~~

Note that this seems to *increase* the code size:

Code size differences: (64-bit Gentoo Linux, gcc-10.2.0-r2, release build

   text    data     bss     dec     hex filename
  23255    3376      72   26703    684f RomDataFactory.cpp.o [before]
  23395    3376      72   26843    68db RomDataFactory.cpp.o
   +140       0       0    +140     +8c Difference