[libromdata] GcnPartitionPrivate::loadFst(): Delete gcnFst, not fst, on error.
fst is this->fst, which is nullptr at this point.

This fixes a memory leak, reported by clang-9.0's AddressSanitizer.:

ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16 byte(s) in 2 object(s) allocated from:
    #0 0x81511e3 in operator new(unsigned int) compiler-rt-9.0.0.src/lib/asan/asan_new_delete.cc:99:3
    #1 0x84e439b in LibRomData::GcnPartitionPrivate::loadFst() src/libromdata/disc/GcnPartitionPrivate.cpp:179:25

Indirect leak of 112 byte(s) in 2 object(s) allocated from:
    #0 0x81511e3 in operator new(unsigned int) compiler-rt-9.0.0.src/lib/asan/asan_new_delete.cc:99:3
    #1 0x8571151 in LibRomData::GcnFst::GcnFst(unsigned char const*, unsigned int, unsigned char) src/libromdata/disc/GcnFst.cpp:377:6