[gtk] RomDataFormat: rom_data_format_dimensions() must have C++ linkage because it returns std::string.
gcc doesn't seem to care, but clang complains very loudly:

In file included from src/gtk/RomDataFormat.cpp:10:
src/gtk/RomDataFormat.hpp:33:1: error: 'rom_data_format_dimensions' has C-linkage specified, but returns user-defined type 'std::string' (aka 'basic_string<char>') which is incompatible with C [-Werror,-Wreturn-type-c-linkage]
   33 | rom_data_format_dimensions(const int dimensions[3]);
      | ^