[gtk] RpGtkCpp.hpp: Use C++ linkage for convert_accel_to_gtk().
clang doesn't allow C linkage for functions that return C++ objects:

In file included from src/gtk/config/ConfigDialog.cpp:15:
src/gtk/xfce/../RpGtkCpp.hpp:21:13: error: 'convert_accel_to_gtk' has
C-linkage specified, but returns user-defined type 'std::string'
(aka 'basic_string<char>') which is incompatible with C
[-Werror,-Wreturn-type-c-linkage]

   21 | std::string convert_accel_to_gtk(const char *str);
      |             ^

1 error generated.