[libwin32common] RpWin32_sdk.h: Add a workaround for the v141_xp toolchain on MSVC 17.14.16.
Attempting to build using v141_xp on MSVC 17.14.16 randomly fails in
objbase.h due to IUnknown not being declared yet:

error C2760: syntax error: unexpected token 'identifier', expected 'type specifier'

Adding a forward-declaration here fixes it.

References:
- https://stackoverflow.com/questions/57014731/gdi-library-causes-error-c2760-syntax-error-unexpected-token-identifier-e
- https://stackoverflow.com/a/62349505