Update packaging scripts for 17.14.16.
[cmake] win32-msvc-arm64x.cmake: Add a faster version that requires
MSVC 17.11 or later. The slower version is still present, and is used
if an older version of MSVC is detected.

Update the 32-bit ARM Win10 toolchain files to require the Windows 10 SDK.
The Windows 11 SDK (10.0.26100.0 and later) does not support 32-bit ARM.
Instead, specify 10.0.19041.0 (the last Windows 10 SDK).

CMake 3.27 is now required for 32-bit ARM builds.

Also, disable C5105 in 32-bit ARM builds due to an issue in winbase.h:

C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9572,5): error C2220: the following warning is treated as an error [build.arm\extlib\zlib-ng\zlib.vcxproj]
  (compiling source file 'extlib/zlib-ng/arch/arm/arm_features.c')

C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9572,5): warning C5105: macro expansion producing 'defined' has undefined behavior [build.arm\extlib\zlib-ng\zlib.vcxproj]
  (compiling source file '../../../../extlib/zlib-ng/arch/arm/arm_features.c')

[scripts] package.cmd: Update version numbers for MSVC 17.11.
Also, don't use parentheses in comments or echo statements, since this
can confuse cmd in some cases.