[librpbase] T_img_vars.hpp: Disable copying in the vars structs.
Not the deleters, though.

T_img_vars_t: Need to add a default constructor. Otherwise, the deleted
copy/assignment constructors break things:

src/kde/DragImageLabel.cpp: In constructor ‘DragImageLabel::DragImageLabel(const QString&, QWidget*, Qt::WindowFlags)’:
src/kde/DragImageLabel.cpp:34:28: error: no matching function for call to ‘LibRpBase::T_img_vars_t<QPixmap, QTimer>::T_img_vars_t()’
   34 |         , m_ecksBawks(false)
      |                            ^
  • there is 1 candidate
In file included from src/kde/kf6/../../librpbase/img/IconAnimData.hpp:11,
                 from src/kde/DragImageLabel.hpp:14,
                 from src/kde/DragImageLabel.cpp:10:
    • candidate 1: ‘LibRpBase::T_img_vars_t<ImgClass, TmrClass, ImgClassDeleter, TmrClassDeleter>::T_img_vars_t(const LibRpBase::T_img_vars_t<ImgClass, TmrClass, ImgClassDeleter, TmrClassDeleter>&) [with ImgClass = QPixmap; TmrClass = QTimer; ImgClassDeleter = LibRpBase::non_pointer_deleter<QPixmap>; TmrClassDeleter = LibRpBase::non_pointer_deleter<QTimer>]’ (deleted)
      src/kde/kf6/../../librpbase/img/T_img_vars.hpp:163:25:
        163 |         RP_DISABLE_COPY(T_img_vars_t);
            |                         ^~~~~~~~~~~~
    • in definition of macro ‘RP_DISABLE_COPY’
        109 |         klass(const klass &) = delete; \
            |         ^~~~~
      • candidate expects 1 argument, 0 provided
      • in definition of macro ‘RP_DISABLE_COPY’
          109 |         klass(const klass &) = delete; \
              |         ^~~~~
src/kde/DragImageLabel.cpp: In constructor ‘DragImageLabel::DragImageLabel(QWidget*, Qt::WindowFlags)’:
src/kde/DragImageLabel.cpp:40:28: error: no matching function for call to ‘LibRpBase::T_img_vars_t<QPixmap, QTimer>::T_img_vars_t()’
   40 |         , m_ecksBawks(false)
      |                            ^
  • there is 1 candidate
    • candidate 1: ‘LibRpBase::T_img_vars_t<ImgClass, TmrClass, ImgClassDeleter, TmrClassDeleter>::T_img_vars_t(const LibRpBase::T_img_vars_t<ImgClass, TmrClass, ImgClassDeleter, TmrClassDeleter>&) [with ImgClass = QPixmap; TmrClass = QTimer; ImgClassDeleter = LibRpBase::non_pointer_deleter<QPixmap>; TmrClassDeleter = LibRpBase::non_pointer_deleter<QTimer>]’ (deleted)
      src/kde/kf6/../../librpbase/img/T_img_vars.hpp:163:25:
        163 |         RP_DISABLE_COPY(T_img_vars_t);
            |                         ^~~~~~~~~~~~
    • in definition of macro ‘RP_DISABLE_COPY’
        109 |         klass(const klass &) = delete; \
            |         ^~~~~
      • candidate expects 1 argument, 0 provided
      • in definition of macro ‘RP_DISABLE_COPY’
          109 |         klass(const klass &) = delete; \
              |         ^~~~~