timeconv.h, bitstuff.h: Fix inverted __cplusplus check.
MSVC complained about this with weird messages in C code:

C:\projects\rom-properties\src\librpbase/timeconv.h(47): error C2433: 'constexpr': 'inline' not permitted on data declarations
C:\projects\rom-properties\src\librpbase/timeconv.h(47): error C2054: expected '(' to follow 'constexpr'
C:\projects\rom-properties\src\librpbase/timeconv.h(48): error C2085: 'WindowsTimeToUnixTime': not in formal parameter list
C:\projects\rom-properties\src\librpbase/timeconv.h(48): error C2143: syntax error: missing ';' before '{'
C:\projects\rom-properties\src\librpbase/timeconv.h(61): error C2433: 'constexpr': 'inline' not permitted on data declarations
C:\projects\rom-properties\src\librpbase/timeconv.h(61): error C2054: expected '(' to follow 'constexpr'
C:\projects\rom-properties\src\librpbase/timeconv.h(62): error C2085: 'WindowsSplitTimeToUnixTime': not in formal parameter list
C:\projects\rom-properties\src\librpbase/timeconv.h(62): error C2143: syntax error: missing ';' before '{'
C:\projects\rom-properties\src\librpbase/timeconv.h(74): error C2433: 'constexpr': 'inline' not permitted on data declarations
C:\projects\rom-properties\src\librpbase/timeconv.h(74): error C2054: expected '(' to follow 'constexpr'
C:\projects\rom-properties\src\librpbase/timeconv.h(75): error C2085: 'UnixTimeToWindowsTime': not in formal parameter list
C:\projects\rom-properties\src\librpbase/timeconv.h(75): error C2143: syntax error: missing ';' before '{'
C:\projects\rom-properties\src\libwin32common/w32time.h(24): error C4013: 'UnixTimeToWindowsTime' undefined; assuming extern returning int
C:\projects\rom-properties\src\libwin32common/w32time.h(51): error C4013: 'WindowsTimeToUnixTime' undefined; assuming extern returning int