[win32] RpFile_IStream.hpp: #include <comdef.h> and <comdefsp.h> for IStreamPtr.
This didn't cause a problem on MSVC, but it broke the MinGW-w64 build:

[ 90%] Building CXX object src/win32/CMakeFiles/rom-properties.dir/RpFile_IStream.cpp.obj
In file included from C:\projects\rom-properties\src\win32\RpFile_IStream.cpp:12:0:
C:\projects\rom-properties\src\win32\RpFile_IStream.hpp:120:3: error: 'IStreamPtr' does not name a type; did you mean 'IStream'?
   IStreamPtr m_pStream;
   ^~~~~~~~~~
   IStream