[librpbase] HashNettle: Remove a duplicate `RP_D(const Hash);`.
This broke the AppVeyor Linux build, and apparently I didn't test it
locally, either...

In file included from src/librpbase/../librpcpu/cpuflags_x86.h:12,
                 from src/librpbase/../librpcpu/byteswap_rp.h:23,
                 from src/librpbase/stdafx.h:66,
                 from src/librpbase/crypto/HashNettle.cpp:9:
src/librpbase/crypto/HashNettle.cpp: In member function ‘bool LibRpBase::Hash::isUsable() const’:
src/librpbase/../common.h:80:45: error: redeclaration of ‘const LibRpBase::HashPrivate* const d’
   80 | #  define RP_D(klass) klass##Private *const d = static_cast<klass##Private*>(d_ptr)
      |                                             ^
src/librpbase/crypto/HashNettle.cpp:113:2: note: in expansion of macro ‘RP_D’
  113 |  RP_D(const Hash);
      |  ^~~~
src/librpbase/../common.h:80:45: note: ‘const LibRpBase::HashPrivate* const d’ previously declared here
   80 | #  define RP_D(klass) klass##Private *const d = static_cast<klass##Private*>(d_ptr)
      |                                             ^
src/librpbase/crypto/HashNettle.cpp:110:2: note: in expansion of macro ‘RP_D’
  110 |  RP_D(const Hash);
      |  ^~~~