[libromdata] Nintendo3DS::loadFieldData(): Fix a libfmt variable binding issue on big-endian.
On big-endian, be32_to_cpu() is a no-op, and the console_id field is
within a packed struct, which causes problems on Debian 8 (gcc-4.9, ppc):

src/libromdata/Handheld/Nintendo3DS.cpp: In member function ‘virtual int LibRomData::Nintendo3DS::loadFieldData()’:
src/libromdata/Handheld/Nintendo3DS.cpp:2117:70: error: cannot bind packed field ‘((LibRomData::Nintendo3DSPrivate*)d)->LibRomData::Nintendo3DSPrivate::mxh.LibRomData::Nintendo3DSPrivate::<anonymous union>::<anonymous>.LibRomData::Nintendo3DSPrivate::<anonymous union>::<anonymous struct>::ticket._N3DS_Ticket_t::console_id’ to ‘unsigned int&’
    fmt::format(FSTR("{:0>8X}"), be32_to_cpu(d->mxh.ticket.console_id)),
                                                                      ^

Adding a unary '+' to be32_to_cpu() fixes this issue.