[libwin32darkmode] DarkMode.cpp: Convert MyOpenThemeData from a lambda function to a static function.
OpenNcThemeData is WINAPI, and gcc doesn't support using non-cdecl
calling conventions on lambda functions.

Note that this only affects the 32-bit i386 Windows build.

src/libwin32darkmode/DarkMode.cpp: In function ‘void FixDarkScrollBar()’:
src/libwin32darkmode/DarkMode.cpp:112:57: error: invalid ‘static_cast’ from type ‘void*(HWND, LPCWSTR)’ {aka ‘void*(HWND__*, const wchar_t*)’} to type ‘fnOpenNcThemeData’ {aka ‘void* (__attribute__((stdcall)) *)(HWND__*, const wchar_t*)’}
  112 |         addr->u1.Function = reinterpret_cast<ULONG_PTR>(static_cast<fnOpenNcThemeData>(MyOpenThemeData));
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~