[libromdata] VectorFile: Export the entire class.
AppVeyor Ubuntu 18.04 was failing to build the XFCE (GTK2) UI frontend
because it couldn't find the VectorFile vtable:

src/gtk/xfce/CMakeFiles/rom-properties-xfce.dir/__/DragImage.cpp.o:
	In function `drag_image_drag_data_get(_DragImage*, _GdkDragContext*, _GtkSelectionData*, unsigned int, unsigned int, void*)':
src/librpfile/VectorFile.hpp:29: undefined reference to `vtable for LibRpFile::VectorFile'

I wouldn't have noticed this without adding --no-undefined because there
aren't any automated UI tests right now. (Well, maybe I would have noticed
it on my Xubuntu 16.04 VM, but maybe not...)

Interestingly, the MSVC builds export *all* of VectorFile's functions,
whereas the gcc builds (even on Windows) don't export the inlined ones.
This probably isn't an issue, since VectorFile function access usually
goes through the vtable, and for cases where it doesn't, the inlined
functions will be inlined.