[kde] Ext2AttrView: Use QString::arg() instead of fmt::format().
fmt::format() worked on my main system, but on Xubuntu 16.04, it didn't
work because the fmt headers aren't included:

src/kde/xattr/Ext2AttrView.cpp: In member function ‘void Ext2AttrViewPrivate::retranslateUi_nonDesigner()’:
src/kde/xattr/Ext2AttrView.cpp:94:13: error: ‘fmt’ has not been declared
   s_label = fmt::format(FRUN(s_lsattr_fmt), p->lsattr_chr,
             ^
src/kde/xattr/Ext2AttrView.cpp:94:42: error: ‘FRUN’ was not declared in this scope
   s_label = fmt::format(FRUN(s_lsattr_fmt), p->lsattr_chr,
                                          ^

We're not linking to fmt in the XAttrView plugin, so use QString::arg()
instead. (I'm guessing CMake auto-magically linked to fmt because
libromdata links to it...)

NOTE: The debug build still links to libfmt-11.so (and a bunch of other
libraries that aren't actually needed). The release build no longer links
to libfmt-11.so. I'm guessing CMake is skipping .so trimming in the debug
builds in order to save time.