[minizip-ng] CMakeLists.txt: FIXME: Fix stringop-overflow and stringop-truncation warnings.
This broke the Ubuntu 22.04 AppVeyor build:

extlib/minizip-ng/mz_zip_rw.c: In function ‘mz_zip_reader_entry_save_file’:
extlib/minizip-ng/mz_zip_rw.c:668:5: error: ‘__builtin_strncat’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  668 |     strncat(pathwfs, path, path_length);
      |     ^
extlib/minizip-ng/mz_zip_rw.c:662:19: note: length computed here
  662 |     path_length = strlen(path);
      |                   ^~~~~~~~~~~~
cc1: all warnings being treated as errors

extlib/minizip-ng/mz_zip.c: In function ‘mz_zip_set_comment’:
extlib/minizip-ng/mz_zip.c:1574:5: error: ‘__builtin_strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
 1574 |     strncpy(zip->comment, comment, comment_size);
      |     ^
extlib/minizip-ng/mz_zip.c:1568:29: note: length computed here
 1568 |     comment_size = (int32_t)strlen(comment);
      |                             ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors