[cmake] CheckZLIB.cmake: Set ZLIB_COMPAT if using the system version of zlib.
This fixes an issue on Fedora 42, which uses zlib-ng system-wide,
which resulted in "undefined reference to 'zlibng_version'".

Also, only set ZLIB_CONST if using the system version, because when
we use our own version, zlib-ng/CMakeLists.txt sets both ZLIB_COMPAT
and ZLIB_CONST.

Fixes #454: Undefined reference to 'zlibng_version'
Reported by @Techokami.