compiler-compat.h: #include "time_r.h" instead of <time.h> for MinGW-w64.
MinGW-w64 has localtime_r() but only if _POSIX_C_SOURCE is deinfed before
including <time.h>.

src/librpbase/TextOut_text.cpp: In function ‘std::string LibRpBase::formatDateTime(rp_time_t, RomFields::DateTimeFlags)’:
src/librpbase/TextOut_text.cpp:476:22: error: ‘localtime_r’ was not declared in this scope; did you mean ‘localtime_s’?
  476 |                 if (!localtime_r(&t, &tm_struct)) {
      |                      ^~~~~~~~~~~
      |                      localtime_s