[win32] thumbcache-wrapper.hpp: Remove EXTERN_C from IID_IThumbnailProvider.
This caused an error in the MinGW-w64 build:

./src/win32/thumbcache-wrapper.hpp:29:1: error: invalid use of 'static' in linkage specification
 static const IID IID_IThumbnailProvider =
 ^~~~~~

C linkage isn't really needed because it's only used within the Win32
rom-properties.dll build and isn't exported.